/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AuthRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthOk"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/usuarios-parceiros": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ListaUsuariosParceirosResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateOpportunityRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreateOpportunityOk"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GetOpportunityOk"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Opportunity"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Opportunity"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/incluir-proposta-integracao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateProposalRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreateProposalOk"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/simulacao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateSimulationRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["CreateSimulationResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/simulacao/{idSimulacao}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          idSimulacao: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateSimulationRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UpdateSimulationResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/simulacao/{idSimulacao}/integracao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          idSimulacao: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SimulationIntegrationResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/incluir-documentos-integracao": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SendDocumentsRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SendDocumentsResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/participante": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateParticipantRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Participant"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{idOportunidade}/participante/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          idOportunidade: string;
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateParticipantRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Participant"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          idOportunidade: string;
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown;
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dominios/bancos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BancosResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dominios/operacoes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OperacoesResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documento/{id}/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "multipart/form-data": components["schemas"]["UploadRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown;
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oportunidade/{id}/follow-up": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["FollowUpRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["FollowUp"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["BasicError"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthRequest: {
      /** @example Secret ID */
      secretId?: string;
      /** @example Secret Key */
      secretKey?: string;
    };
    AuthOk: {
      /** @example JWT Session token */
      jwt?: string;
      /** @example JWT Refresh token */
      refreshToken?: string;
      usuario?: {
        /** @example Nome do usuário autenticado */
        nome?: string;
        /** @example Perfil do usuário autenticado */
        perfil?: string;
        /** @example ID do parceiro */
        idParceiro?: string;
        /** @example ID da regional */
        idRegional?: string;
        /** @example ID do usuário parceiro */
        idUsuarioParceiro?: string;
        /** @example Nome do usuário parceiro */
        nomeUsuarioParceiro?: string;
        /** @example Telefone do usuário parceiro */
        telefoneUsuarioParceiro?: string;
      };
    };
    CreateOpportunityRequest: {
      operacao?: {
        /** @example 123 (Obtido no serviço de domínio '/dominios/operacoes') */
        idOperacao?: string;
      };
      regional?: {
        /** @example 123 (obtido no serviço de autenticação) */
        idRegional?: string;
      };
      parceiro?: {
        /** @example 123 (obtido no serviço de autenticação) */
        idParceiro?: string;
      };
      usuarioParceiro?: {
        /** @example 123 (obtido no serviço de autenticação) */
        idUsuarioParceiro?: string;
      };
      tipoImovel?: {
        /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
        id?: string;
      };
      usoImovel?: {
        /** @example C/R (Comercial/Residencial) */
        id?: string;
      };
      uf?: {
        /** @example Sigla da UF do imóvel */
        codigo?: string;
      };
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamento?: number;
      /** @example 123 */
      prazo?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      bancos?: {
        /** @example 123 */
        idBanco?: number;
        /** @example 123 */
        codigoBanco?: number;
        /** @example Nome do Banco */
        nomeBanco?: string;
        /** @example S/N */
        flagSimulacao?: string;
      }[];
      /** @example 12345678909 (apenas números) */
      cpfCnpj?: string;
      /** @example Nome do cliente */
      nome?: string;
      /** @example 12345.67 */
      rendaTotal?: number;
      codigoSistemaAmortizacaoBanco?: {
        /** @example S/P (SAC/PRICE) */
        id?: string;
      };
      /** @example yyyy-MM-dd */
      dataNascimento?: string;
      /** @example a@b.com.br */
      email?: string;
      /** @example 11912345678 (somente números) */
      celular?: string;
      /** @example true */
      fgCompoeRenda?: boolean;
      /** @example 12345678909 (apenas números) */
      cpfConjuge?: string;
      /** @example Nome do cônjuge */
      nomeConjuge?: string;
      /** @example a@b.com.br */
      emailConjuge?: string;
      /** @example 11912345678 (somente números) */
      celularConjuge?: string;
      /** @example 12345.67 */
      rendaConjuge?: number;
      /** @example yyyy-MM-dd */
      dataNascimentoConjuge?: string;
      situacaoImovel?: {
        /** @example N/U (Novo/Usado) */
        codigo?: string;
      };
      /** @example S/N */
      fgFinanciarDespesas?: string;
      tipoEstadoCivilConjuge?: {
        /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
        id?: string;
      };
      tipoEstadoCivil?: {
        /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
        id?: string;
      };
    };
    CreateParticipantRequest: {
      /** @example A/I (Ativa/Inativa) */
      tipoSituacao?: string;
      /** @example Nome do participante */
      nomeParticipante?: string;
      /** @example CO/VD (Comprador/Vendedor) */
      tipoQualificacao?: string;
      /** @example F/J (Física/Jurídica) */
      tipoPessoa?: string;
      /** @example 12345678909 (apenas números) */
      cpfCnpj?: string;
      /** @example yyyy-MM-dd */
      dataNascimento?: string;
      /** @example Nome da mãe do participante */
      nomeMae?: string;
      /** @example M/F (Masculino/Feminino) */
      tipoSexo?: string;
      /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
      tipoEstadoCivil?: string;
      /** @example CP/CU/PA/SC/SO (Comunhão Parcial de Bens/Comunhão Universal de Bens/Participação Final nos Aquestos/Separação Convencional de Bens/Separação Obrigatória de Bens) */
      tipoRegimeCasamento?: string;
      /** @example RG/CNH */
      tipoDocumentoIdentidade?: string;
      /** @example Número do documento do participante */
      numeroDocumento?: string;
      /** @example yyyy-MM-dd */
      dataExpedicao?: string;
      /** @example Órgão expedidor do documento do participante */
      orgaoExpedidor?: string;
      /** @example UF expedidor do documento do participante */
      ufExpedicao?: string;
      /** @example Profissão do participante */
      nomeProfissao?: string;
      /** @example Empresa da profissão do participante */
      nomeEmpresaProfissao?: string;
      /** @example 123456.78 */
      renda?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example 1234 */
      codigoAgencia?: string;
      /** @example 001910123 */
      codigoContaCorrente?: string;
      /** @example 4 */
      digitoContaCorrente?: string;
      /** @example a@b.com.br */
      email?: string;
      /** @example 11912345678 (somente números) */
      celular?: string;
      /** @example 00000000 */
      cep?: string;
      /** @example Logradouro do participante */
      logradouro?: string;
      /** @example Número do participante */
      numeroLogradouro?: string;
      /** @example Complemento do participante */
      complementoLogradouro?: string;
      /** @example Bairro do participante */
      bairro?: string;
      /** @example Município do participante */
      municipio?: string;
      /** @example UF do participante */
      uf?: string;
      /** @example SA/EPP/ME/MEI/EIRELI */
      tipoEmpresa?: string;
      /** @example yyyy-MM-dd */
      dataRegistroEmpresa?: string;
      /** @example 12345678.9 */
      faturamentoEmpresa?: number;
      /** @example 12345678.9 */
      patrimonioLiquidoEmpresa?: number;
      /** @example 12345678.9 */
      capitalSocialEmpresa?: number;
      /** @example S/N */
      utilizaFgts?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example Nome do cônjuge */
      nomeConjuge?: string;
      /** @example 12345678909 (apenas números) */
      cpfConjuge?: string;
      /** @example yyyy-MM-dd */
      dataNascimentoConjuge?: string;
      /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
      tipoEstadoCivilConjuge?: string;
      /** @example RG/CNH */
      tipoDocumentoIdentidadeConjuge?: string;
      /** @example Número do documento do conjuge */
      numeroDocumentoConjuge?: string;
      /** @example yyyy-MM-dd */
      dataExpedicaoConjuge?: string;
      /** @example Órgão expedidor do documento do conjuge */
      orgaoExpedidorConjuge?: string;
      /** @example UF expedidor do documento do conjuge */
      ufExpedicaoConjuge?: string;
      /** @example Profissão do conjuge */
      nomeProfissaoConjuge?: string;
      /** @example 123456.78 */
      rendaConjuge?: number;
      /** @example Empresa da profissão do conjuge */
      nomeEmpresaProfissaoConjuge?: string;
      /** @example M/F (Masculino/Feminino) */
      tipoSexoConjuge?: string;
    };
    UpdateParticipantRequest: components["schemas"]["CreateParticipantRequest"];
    Participant: {
      /** @example 123 */
      idParticipante?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example A/I (Ativa/Inativa) */
      tipoSituacao?: string;
      /** @example Nome do participante */
      nomeParticipante?: string;
      /** @example CO/VD (Comprador/Vendedor) */
      tipoQualificacao?: string;
      /** @example F/J (Física/Jurídica) */
      tipoPessoa?: string;
      /** @example 00000000000 (somente numeros) */
      cpfCnpj?: string;
      /** @example yyyy-MM-dd */
      dataNascimento?: string;
      /** @example M/F (Masculino/Feminino) */
      tipoSexo?: string;
      /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
      tipoEstadoCivil?: string;
      /** @example CP/CU/PA/SC/SO (Comunhão Parcial de Bens/Comunhão Universal de Bens/Participação Final nos Aquestos/Separação Convencional de Bens/Separação Obrigatória de Bens) */
      tipoRegimeCasamento?: string;
      /** @example RG/CNH */
      tipoDocumentoIdentidade?: string;
      /** @example Número do documento do participante */
      numeroDocumento?: string;
      /** @example yyyy-MM-dd */
      dataExpedicao?: string;
      /** @example Órgão expedidor do documento do participante */
      orgaoExpedidor?: string;
      /** @example UF expedidor do documento do participante */
      ufExpedicao?: string;
      /** @example Nome da mãe do participante */
      nomeMae?: string;
      /** @example Profissão do participante */
      nomeProfissao?: string;
      /** @example 123456.78 */
      renda?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example 1234 */
      codigoAgencia?: string;
      /** @example 001910123 */
      codigoContaCorrente?: string;
      /** @example 4 */
      digitoContaCorrente?: string;
      /** @example S/N */
      compradorPrincipal?: string;
      /** @example a@b.com.br */
      email?: string;
      /** @example 11912345678 (somente números) */
      celular?: string;
      /** @example 00000000 */
      cep?: string;
      /** @example Logradouro do participante */
      logradouro?: string;
      /** @example Número do participante */
      numeroLogradouro?: string;
      /** @example Complemento do participante */
      complementoLogradouro?: string;
      /** @example Bairro do participante */
      bairro?: string;
      /** @example Município do participante */
      municipio?: string;
      /** @example UF do participante */
      uf?: string;
      /** @example SA/EPP/ME/MEI/EIRELI */
      tipoEmpresa?: string;
      /** @example yyyy-MM-dd */
      dataRegistroEmpresa?: string;
      /** @example 12345678.9 */
      faturamentoEmpresa?: number;
      /** @example 12345678.9 */
      patrimonioLiquidoEmpresa?: number;
      /** @example 12345678.9 */
      capitalSocialEmpresa?: number;
      /** @example Nome do conjuge */
      nomeConjuge?: string;
      /** @example 00000000000 (somente numeros) */
      cpfConjuge?: string;
      /** @example yyyy-MM-dd */
      dataNascimentoConjuge?: string;
      /** @example CA/S/VI/DI/SL/UE (Casado(a)/Solteiro(a)/Viúvo(a)/Divorciado(a)/Separado(a) Legalmente/União Estável) */
      tipoEstadoCivilConjuge?: string;
      /** @example RG/CNH */
      tipoDocumentoIdentidadeConjuge?: string;
      /** @example Número do documento do conjuge */
      numeroDocumentoConjuge?: string;
      /** @example yyyy-MM-dd */
      dataExpedicaoConjuge?: string;
      /** @example Órgão expedidor do documento do conjuge */
      orgaoExpedidorConjuge?: string;
      /** @example UF expedidor do documento do conjuge */
      ufExpedicaoConjuge?: string;
      /** @example yyyy-MM-dd */
      dataInativacao?: string;
      /** @example 123 */
      idUsuarioInativacao?: number;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example 123 */
      idUsuarioAlteracao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraAlteracao?: string;
      /** @example Empresa da profissão do participante */
      nomeEmpresaProfissao?: string;
      /** @example S/N */
      utilizaFgts?: string;
      /** @example Profissão do conjuge */
      nomeProfissaoConjuge?: string;
      /** @example 123456.78 */
      rendaConjuge?: number;
      /** @example Empresa da profissão do conjuge */
      nomeEmpresaProfissaoConjuge?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example M/F (Masculino/Feminino) */
      tipoSexoConjuge?: string;
    };
    Opportunity: {
      /** @example 1234 */
      idOportunidade?: number;
      /** @example Código da oportunidade no sistema */
      codigoOportunidade?: string;
      /** @example 123 */
      idOperacao?: number;
      /** @example yyyy-MM-dd */
      dataOportunidade?: string;
      /** @example A/T/C (Ativa/Contrato Emitido/Cancelada) */
      tipoSituacao?: string;
      /** @example 123 */
      idRegional?: number;
      /** @example 123 */
      idParceiro?: number;
      /** @example 123 */
      idUsuarioParceiro?: number;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 00000000 */
      cep?: string;
      /** @example Logradouro do imóvel */
      logradouro?: string;
      /** @example Número do imóvel */
      numeroLogradouro?: string;
      /** @example Complemento do imóvel */
      complementoLogradouro?: string;
      /** @example Bairro do imóvel */
      bairro?: string;
      /** @example Município do imóvel */
      municipio?: string;
      /** @example UF do imóvel */
      uf?: string;
      /** @example Nome do contato da avaliação */
      contatoAvaliacao?: string;
      /** @example Telefone do contato da avaliação (somente números) */
      telefoneContatoAvaliacao?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example 123 */
      idBancoEscolhido?: number;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      sistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      indexadorBanco?: string;
      /** @example Nome do Interveniente Quitante */
      nomeIntervenienteQuitante?: string;
      /** @example Descrição para processo de Interveniente Quitante */
      descricaoIntervenienteQuitante?: string;
      /** @example Q/M/F (Quente/Morna/Fria) */
      tipoTemperatura?: string;
      /** @example yyyy-MM-dd */
      dataPrevistaEmissaoContrato?: string;
      /** @example yyyy-MM-dd */
      dataCancelamento?: string;
      /** @example 123 */
      idUsuarioCancelamento?: number;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example 123 */
      idUsuarioAlteracao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraAlteracao?: string;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
    };
    CreateOpportunityOk: {
      oportunidade?: components["schemas"]["Opportunity"];
    };
    OpportunityFull: {
      /** @example 1234 */
      idOportunidade?: number;
      /** @example Código da oportunidade no sistema */
      codigoOportunidade?: string;
      /** @example 123 */
      idOperacao?: number;
      /** @example yyyy-MM-dd */
      dataOportunidade?: string;
      /** @example A/T/C (Ativa/Contrato Emitido/Cancelada) */
      tipoSituacao?: string;
      /** @example 123 */
      idRegional?: number;
      /** @example 123 */
      idParceiro?: number;
      /** @example 123 */
      idUsuarioParceiro?: number;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 00000000 */
      cep?: string;
      /** @example Logradouro do imóvel */
      logradouro?: string;
      /** @example Número do imóvel */
      numeroLogradouro?: string;
      /** @example Complemento do imóvel */
      complementoLogradouro?: string;
      /** @example Bairro do imóvel */
      bairro?: string;
      /** @example Município do imóvel */
      municipio?: string;
      /** @example UF do imóvel */
      uf?: string;
      /** @example Nome do contato da avaliação */
      contatoAvaliacao?: string;
      /** @example Telefone do contato da avaliação (somente números) */
      telefoneContatoAvaliacao?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example 123 */
      idBancoEscolhido?: number;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      sistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      indexadorBanco?: string;
      /** @example Nome do Interveniente Quitante */
      nomeIntervenienteQuitante?: string;
      /** @example Descrição para processo de Interveniente Quitante */
      descricaoIntervenienteQuitante?: string;
      /** @example Q/M/F (Quente/Morna/Fria) */
      tipoTemperatura?: string;
      /** @example yyyy-MM-dd */
      dataPrevistaEmissaoContrato?: string;
      /** @example yyyy-MM-dd */
      dataCancelamento?: string;
      /** @example 123 */
      idUsuarioCancelamento?: number;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example 123 */
      idUsuarioAlteracao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraAlteracao?: string;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      simulacoes?: {
        /** @example 123 */
        idSimulacao?: number;
        /** @example 123 */
        idOportunidade?: number;
        /** @example 123 */
        idBanco?: number;
        /** @example yyyy-MM-dd */
        dataSimulacao?: string;
        /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
        tipoImovel?: string;
        /** @example C/R (Comercial/Residencial) */
        tipoUtilizacaoImovel?: string;
        /** @example 123456.78 */
        valorImovel?: number;
        /** @example 123456.78 */
        valorFinanciamentoSimulacao?: number;
        /** @example 123456.78 */
        valorParcelaSimulacao?: number;
        /** @example 123 */
        prazoPagamentoSimulacao?: number;
        /** @example S/N */
        utilizaFgtsSimulacao?: string;
        /** @example S/P/N/A/R (Sem Integração/Erro ao Enviar Proposta/Análise Crédito/Crédito Aprovado/Crédito Recusado) */
        tipoSituacao?: string;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraEnvioIntegracao?: string;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraRetornoIntegracao?: string;
        /** @example S/N */
        bancoEscolhido?: string;
        /** @example Código da oportunidade no banco */
        codigoOportunidadeBanco?: string;
        /** @example 123456.78 */
        valorFinanciamentoBanco?: number;
        /** @example 123456.78 */
        valorParcelaBanco?: number;
        /** @example 123 */
        prazoPagamentoBanco?: number;
        /** @example 123456.78 */
        valorFinanciamentoBancoMax?: number;
        /** @example 123456.78 */
        valorParcelaBancoMax?: number;
        /** @example 123 */
        prazoPagamentoBancoMax?: number;
        /** @example 12.34 */
        taxaJurosAnoBanco?: number;
        /** @example 123456.78 */
        valorIofBanco?: number;
        /** @example S/P (SAC/PRICE) */
        codigoSistemaAmortizacaoBanco?: string;
        /** @example Indexador da Operação no retorno do Banco Escolhido */
        codigoIndexadorBanco?: string;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example N/U (Novo/Usado) */
        situacaoImovel?: string;
        /** @example S/N */
        fgFinanciarDespesas?: string;
        /** @example 1234 */
        agencia?: string;
        /** @example 12313 */
        conta?: string;
        /** @example 1 */
        digito?: string;
        /** @example 123456.78 */
        valorDespesasFinanciadas?: number;
        /** @example 123456.78 */
        valorTotalFinanciamento?: number;
        /** @example Retorno da integração */
        retornoIntegracao?: string;
        /** @example true */
        fgAutorizacaoDados?: boolean;
        /** @example Código de situação retornado pelo banco */
        codigoSituacaoBanco?: string;
        banco?: {
          /** @example 123 */
          idBanco?: number;
          /** @example 123 */
          codigoBanco?: number;
          /** @example Nome do Banco */
          nomeBanco?: string;
          /** @example S/N */
          flagSimulacao?: string;
        };
      }[];
      participantes?: components["schemas"]["Participant"][];
      regional?: {
        /** @example 123 */
        idRegional?: number;
        /** @example Nome da regional */
        nomeRegional?: string;
        /** @example 1234567890123456 (somente números) */
        cnpj?: string;
        /** @example 00000000 */
        cep?: string;
        /** @example Logradouro da regional */
        logradouro?: string;
        /** @example Número da regional */
        numeroLogradouro?: string;
        /** @example Complemento da regional */
        complementoLogradouro?: string;
        /** @example Bairro da regional */
        bairro?: string;
        /** @example Município da regional */
        municipio?: string;
        /** @example UF da regional */
        uf?: string;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAlteracao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAlteracao?: string;
      };
      parceiro?: {
        /** @example 123 */
        idParceiro?: number;
        /** @example Razão social do parceiro */
        nomeParceiro?: string;
        /** @example 1234567890123456 (somente números) */
        cpfCnpj?: string;
        /** @example RM/IN/PR/ST/MK (REMAX/Indicação/Prospecção/Site/Marketing) */
        tipoOrigem?: string;
        /** @example Nome do proprietário */
        nomeProprietario?: string;
        /** @example Email do proprietário */
        emailProprietario?: string;
        /** @example Telefone do proprietário */
        celularProprietario?: string;
        /** @example Nome da pessoa que cuida do faturamento */
        nomeFaturamento?: string;
        /** @example E-mail de faturamento */
        emailFaturamento?: string;
        /** @example Telefone de faturamento */
        celularFaturamento?: string;
        /** @example 00000000 */
        cep?: string;
        /** @example Logradouro do parceiro */
        logradouro?: string;
        /** @example Número do parceiro */
        numeroLogradouro?: string;
        /** @example Complemento do parceiro */
        complementoLogradouro?: string;
        /** @example Bairro do parceiro */
        bairro?: string;
        /** @example Município do parceiro */
        municipio?: string;
        /** @example UF do parceiro */
        uf?: string;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAlteracao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAlteracao?: string;
        /** @example 123 */
        idRegional?: number;
        /** @example A/I (Ativa/Inativa) */
        tipoSituacao?: string;
        /** @example AS/IM/CO/CA (Assessoria/Imobiliária/Corretor/Cartório) */
        perfil?: string;
      };
      bancoEscolhido?: {
        /** @example 123 */
        idBanco?: number;
        /** @example 123 */
        codigoBanco?: number;
        /** @example Nome do Banco */
        nomeBanco?: string;
        /** @example S/N */
        flagSimulacao?: string;
      };
      operacao?: {
        /** @example 123 */
        idOperacao?: number;
        /** @example Nome do Produto */
        nomeOperacao?: string;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAlteracao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAlteracao?: string;
        /** @example A/I (Ativa/Inativa) */
        tipoSituacao?: string;
      };
      usuarioParceiro?: {
        /** @example 123 */
        idUsuarioParceiro?: number;
        /** @example Razão social do parceiro */
        nomeUsuarioParceiro?: string;
        /** @example 1234567890123456 (somente números) */
        cpfCnpj?: string;
        /** @example RM/IN/PR/ST/MK (REMAX/Indicação/Prospecção/Site/Marketing) */
        tipoOrigem?: string;
        /** @example Nome do proprietário */
        nomeProprietario?: string;
        /** @example Email do proprietário */
        emailProprietario?: string;
        /** @example Telefone do proprietário */
        celularProprietario?: string;
        /** @example Nome da pessoa que cuida do faturamento */
        nomeFaturamento?: string;
        /** @example E-mail de faturamento */
        emailFaturamento?: string;
        /** @example Telefone de faturamento */
        celularFaturamento?: string;
        /** @example 00000000 */
        cep?: string;
        /** @example Logradouro do parceiro */
        logradouro?: string;
        /** @example Número do parceiro */
        numeroLogradouro?: string;
        /** @example Complemento do parceiro */
        complementoLogradouro?: string;
        /** @example Bairro do parceiro */
        bairro?: string;
        /** @example Município do parceiro */
        municipio?: string;
        /** @example UF do parceiro */
        uf?: string;
        /** @example 123 */
        idUsuarioConsultor?: number;
        /** @example 123 */
        idUsuarioAnalista?: number;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAlteracao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAlteracao?: string;
        /** @example 123 */
        idParceiro?: number;
        /** @example A/I (Ativa/Inativa) */
        tipoSituacao?: string;
        /** @example AS/IM/CO/CA (Assessoria/Imobiliária/Corretor/Cartório) */
        perfil?: string;
      };
      atividadesOportunidade?: {
        /** @example 123 */
        idAtividadeOportunidade?: number;
        /** @example 123 */
        idOportunidade?: number;
        /** @example 123 */
        idAtividade?: number;
        /** @example A/M (Automática/Manual) */
        tipoFormaInclusao?: string;
        /** @example yyyy-MM-dd */
        dataInclusao?: string;
        /** @example yyyy-MM-dd */
        dataPrevisaoConclusao?: string;
        /** @example N/E/C (Não Iniciada/Em Andamento/Concluída) */
        tipoSituacao?: string;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAtuacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAtuacao?: string;
        /** @example 123 */
        idUsuarioConclusao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraConclusao?: string;
        /** @example 123 */
        idEtapa?: number;
        atividade?: {
          /** @example 123 */
          idAtividade?: number;
          /** @example Nome da atividade */
          nomeAtividade?: string;
          /** @example 123 */
          idEtapa?: number;
          /** @example A/I (Ativa/Inativa) */
          tipoSituacao?: string;
          /** @example 123 */
          ordemAtividade?: number;
          /** @example 123 */
          diasSla?: number;
          /** @example 123 */
          idUsuarioCriacao?: number;
          /** @example yyyy-MM-dd HH:mm:ss */
          dataHoraCriacao?: string;
          /** @example 123 */
          idUsuarioAlteracao?: number;
          /** @example yyyy-MM-dd HH:mm:ss */
          dataHoraAlteracao?: string;
          /** @example S/N */
          flagEmissaoContrato?: string;
        };
        etapa?: {
          /** @example 123 */
          idEtapa?: number;
          /** @example Nome da etapa */
          nomeEtapa?: string;
          /** @example 123 */
          idOperacao?: number;
          /** @example A/I (Ativa/Inativa) */
          tipoSituacao?: string;
          /** @example 123 */
          ordemEtapa?: number;
          /** @example 123 */
          idUsuarioCriacao?: number;
          /** @example yyyy-MM-dd HH:mm:ss */
          dataHoraCriacao?: string;
          /** @example 123 */
          idUsuarioAlteracao?: number;
          /** @example yyyy-MM-dd HH:mm:ss */
          dataHoraAlteracao?: string;
        };
      }[];
    };
    GetOpportunityOk: {
      oportunidade?: components["schemas"]["OpportunityFull"];
      etapa?: {
        /** @example 123 */
        idEtapa?: number;
        /** @example Nome da etapa */
        nomeEtapa?: string;
        /** @example 123 */
        idOperacao?: number;
        /** @example A/I (Ativa/Inativa) */
        tipoSituacao?: string;
        /** @example 123 */
        ordemEtapa?: number;
        /** @example 123 */
        idUsuarioCriacao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraCriacao?: string;
        /** @example 123 */
        idUsuarioAlteracao?: number;
        /** @example yyyy-MM-dd HH:mm:ss */
        dataHoraAlteracao?: string;
        /** @example true */
        active?: boolean;
        /** @example true */
        completed?: boolean;
      }[];
    };
    BancosResponse: {
      /** @example 123 */
      idBanco?: number;
      /** @example 123 */
      codigoBanco?: number;
      /** @example Nome do Banco */
      nomeBanco?: string;
      /** @example S/N */
      flagSimulacao?: string;
    }[];
    OperacoesResponse: {
      /** @example 123 */
      idOperacao?: number;
      /** @example Nome do Produto */
      nomeOperacao?: string;
    }[];
    FollowUpRequest: {
      /** @example 123 */
      idOportunidade?: number;
      /** @example I/E (Interno/Externo) */
      tipoFup?: string;
      /** @example Título do follow-up */
      titulo?: string;
      /** @example Texto do follow-up */
      comentario?: string;
    };
    FollowUp: {
      /** @example 123 */
      idFupOportunidade?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example I/E (Interno/Externo) */
      tipoFup?: string;
      /** @example Título do follow-up */
      titulo?: string;
      /** @example Texto do follow-up */
      comentario?: string;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
    };
    CreateProposalRequest: {
      /** @example 123 */
      idSimulacao?: number;
    };
    CreateProposalOk: {
      /** @example 123 */
      idSimulacao?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example yyyy-MM-dd */
      dataSimulacao?: string;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example S/P/N/A/R (Sem Integração/Erro ao Enviar Proposta/Análise Crédito/Crédito Aprovado/Crédito Recusado) */
      tipoSituacao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraEnvioIntegracao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraRetornoIntegracao?: string;
      /** @example S/N */
      bancoEscolhido?: string;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 1234 */
      agencia?: string;
      /** @example 12313 */
      conta?: string;
      /** @example 1 */
      digito?: string;
      /** @example 123456.78 */
      valorDespesasFinanciadas?: number;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      /** @example Retorno da integração */
      retornoIntegracao?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example Código de situação retornado pelo banco */
      codigoSituacaoBanco?: string;
      banco?: {
        /** @example 123 */
        idBanco?: number;
        /** @example 123 */
        codigoBanco?: number;
        /** @example Nome do Banco */
        nomeBanco?: string;
        /** @example S/N */
        flagSimulacao?: string;
      };
    };
    SendDocumentsRequest: {
      /** @example 123 */
      idSimulacao?: number;
    };
    SendDocumentsResponse: {
      sucesso?: {
        /** @example 123 */
        id?: number;
        /** @example 123 */
        codigoGrupoDocumento?: number;
        /** @example 123 */
        codigoIntegracao?: string;
        /** @example 12345678909 */
        cpfCnpj?: string;
        /** @example Nome do documento */
        nomeDocumento?: string;
        /** @example Nome do participante */
        nomeParticipante?: string;
      }[];
      error?: {
        /** @example 123 */
        id?: number;
        /** @example 123 */
        codigoGrupoDocumento?: number;
        /** @example 123 */
        codigoIntegracao?: string;
        /** @example 12345678909 */
        cpfCnpj?: string;
        /** @example Nome do documento */
        nomeDocumento?: string;
        /** @example Nome do participante */
        nomeParticipante?: string;
        /** @example Mensagem de erro */
        erroIntegracao?: string;
      }[];
    };
    BasicError: {
      /** @example Error code */
      code?: string;
      /** @example Some message */
      message?: string;
    };
    /** @enum {string} */
    SituacaoIntegracaoDocumento: "pending" | "success" | "error";
    CreateSimulationRequest: {
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamento?: number;
      /** @example 123 */
      prazo?: number;
      codigoSistemaAmortizacaoBanco?: {
        /** @example S/P (SAC/PRICE) */
        id?: string;
      };
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 12345.67 */
      valorParcelaBanco?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 12345.67 */
      valorIofBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 12345.67 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      banco?: {
        /** @example 123 */
        idBanco?: number;
      };
      /** @example true */
      fgAutorizacaoDados?: boolean;
    };
    ListaUsuariosParceirosResponse: {
      /** @example 123 */
      idUsuarioParceiro?: number;
      /** @example Nome do Usuário Parceiro */
      nomeUsuarioParceiro?: string;
      /** @example 12345678909 (somente números) */
      cpfCnpj?: string;
      /** @example Nome do Proprietário */
      nomeProprietario?: string;
      /** @example a@b.com.br */
      emailProprietario?: string;
      /** @example 11912345678 */
      celularProprietario?: string;
      /** @example Nome do Responsável pelo Faturamento */
      nomeFaturamento?: string;
      /** @example a@b.com.br */
      emailFaturamento?: string;
      /** @example 11912345678 */
      celularFaturamento?: string;
      /** @example A/I (Ativa/Inativa) */
      tipoSituacao?: string;
    }[];
    CreateSimulationResponse: {
      /** @example 123 */
      idSimulacao?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example yyyy-MM-dd */
      dataSimulacao?: string;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example S/P/N/A/R (Sem Integração/Erro ao Enviar Proposta/Análise Crédito/Crédito Aprovado/Crédito Recusado) */
      tipoSituacao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraEnvioIntegracao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraRetornoIntegracao?: string;
      /** @example S/N */
      bancoEscolhido?: string;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 1234 */
      agencia?: string;
      /** @example 12313 */
      conta?: string;
      /** @example 1 */
      digito?: string;
      /** @example 123456.78 */
      valorDespesasFinanciadas?: number;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      /** @example Retorno da integração */
      retornoIntegracao?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example Código de situação retornado pelo banco */
      codigoSituacaoBanco?: string;
    };
    UpdateSimulationRequest: {
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamento?: number;
      /** @example 123 */
      prazo?: number;
      codigoSistemaAmortizacaoBanco?: {
        /** @example S/P (SAC/PRICE) */
        id?: string;
      };
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 12345.67 */
      valorParcelaBanco?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 12345.67 */
      valorIofBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 12345.67 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 123456.78 */
      valorDespesasFinanciadas?: number;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
    };
    UpdateSimulationResponse: {
      /** @example 123 */
      idSimulacao?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example yyyy-MM-dd */
      dataSimulacao?: string;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example S/P/N/A/R (Sem Integração/Erro ao Enviar Proposta/Análise Crédito/Crédito Aprovado/Crédito Recusado) */
      tipoSituacao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraEnvioIntegracao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraRetornoIntegracao?: string;
      /** @example S/N */
      bancoEscolhido?: string;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 1234 */
      agencia?: string;
      /** @example 12313 */
      conta?: string;
      /** @example 1 */
      digito?: string;
      /** @example 123456.78 */
      valorDespesasFinanciadas?: number;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      /** @example Retorno da integração */
      retornoIntegracao?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example Código de situação retornado pelo banco */
      codigoSituacaoBanco?: string;
    };
    SimulationIntegrationResponse: {
      /** @example 123 */
      idSimulacao?: number;
      /** @example 123 */
      idOportunidade?: number;
      /** @example 123 */
      idBanco?: number;
      /** @example yyyy-MM-dd */
      dataSimulacao?: string;
      /** @example AP/CS/GA/TE/TC (Apartamento/Casa/Galpão/Terreno/Terreno em Condomínio) */
      tipoImovel?: string;
      /** @example C/R (Comercial/Residencial) */
      tipoUtilizacaoImovel?: string;
      /** @example 123456.78 */
      valorImovel?: number;
      /** @example 123456.78 */
      valorFinanciamentoSimulacao?: number;
      /** @example 123456.78 */
      valorParcelaSimulacao?: number;
      /** @example 123 */
      prazoPagamentoSimulacao?: number;
      /** @example S/N */
      utilizaFgtsSimulacao?: string;
      /** @example S/P/N/A/R (Sem Integração/Erro ao Enviar Proposta/Análise Crédito/Crédito Aprovado/Crédito Recusado) */
      tipoSituacao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraEnvioIntegracao?: string;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraRetornoIntegracao?: string;
      /** @example S/N */
      bancoEscolhido?: string;
      /** @example Código da oportunidade no banco */
      codigoOportunidadeBanco?: string;
      /** @example 123456.78 */
      valorFinanciamentoBanco?: number;
      /** @example 123456.78 */
      valorParcelaBanco?: number;
      /** @example 123 */
      prazoPagamentoBanco?: number;
      /** @example 123456.78 */
      valorFinanciamentoBancoMax?: number;
      /** @example 123456.78 */
      valorParcelaBancoMax?: number;
      /** @example 123 */
      prazoPagamentoBancoMax?: number;
      /** @example 12.34 */
      taxaJurosAnoBanco?: number;
      /** @example 123456.78 */
      valorIofBanco?: number;
      /** @example S/P (SAC/PRICE) */
      codigoSistemaAmortizacaoBanco?: string;
      /** @example Indexador da Operação no retorno do Banco Escolhido */
      codigoIndexadorBanco?: string;
      /** @example 123 */
      idUsuarioCriacao?: number;
      /** @example yyyy-MM-dd HH:mm:ss */
      dataHoraCriacao?: string;
      /** @example N/U (Novo/Usado) */
      situacaoImovel?: string;
      /** @example S/N */
      fgFinanciarDespesas?: string;
      /** @example 1234 */
      agencia?: string;
      /** @example 12313 */
      conta?: string;
      /** @example 1 */
      digito?: string;
      /** @example 123456.78 */
      valorDespesasFinanciadas?: number;
      /** @example 123456.78 */
      valorTotalFinanciamento?: number;
      /** @example Retorno da integração */
      retornoIntegracao?: string;
      /** @example true */
      fgAutorizacaoDados?: boolean;
      /** @example Código de situação retornado pelo banco */
      codigoSituacaoBanco?: string;
    };
    UploadRequest: {
      /** Format: binary */
      arquivo?: string;
      /** @default false */
      documentoAprovado: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
