/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as ParceiroRouteImport } from './routes/parceiro'
import { Route as ClienteConsentimentoRouteImport } from './routes/cliente-consentimento'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParceiroSimulacoesRouteImport } from './routes/parceiro.simulacoes'
import { Route as ParceiroPropostasRouteImport } from './routes/parceiro.propostas'
import { Route as ParceiroDocumentosRouteImport } from './routes/parceiro.documentos'
import { Route as ParceiroComissoesRouteImport } from './routes/parceiro.comissoes'
import { Route as ParceiroClientesRouteImport } from './routes/parceiro.clientes'
import { Route as ClienteVisaoGeralRouteImport } from './routes/cliente.visao-geral'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ClienteLogoutRouteImport } from './routes/cliente.logout'
import { Route as ClienteChatRouteImport } from './routes/cliente.chat'
import { Route as ClienteAcompanharMinhaPropostaRouteImport } from './routes/cliente.acompanhar-minha-proposta'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedParceiroInicioRouteImport } from './routes/_authenticated/parceiro-inicio'
import { Route as AuthenticatedMatriculasRouteImport } from './routes/_authenticated/matriculas'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedFormulariosRouteImport } from './routes/_authenticated/formularios'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios.index'
import { Route as AuthenticatedFormulariosIndexRouteImport } from './routes/_authenticated/formularios.index'
import { Route as ApiPublicSyncPropostasRouteImport } from './routes/api/public/sync-propostas'
import { Route as AuthenticatedVisaoGeralPainelRouteImport } from './routes/_authenticated/visao-geral.painel'
import { Route as AuthenticatedRelatoriosTarefasRouteImport } from './routes/_authenticated/relatorios.tarefas'
import { Route as AuthenticatedRelatoriosSimulacoesRouteImport } from './routes/_authenticated/relatorios.simulacoes'
import { Route as AuthenticatedRelatoriosPropostasRouteImport } from './routes/_authenticated/relatorios.propostas'
import { Route as AuthenticatedRelatoriosPersonalizadosRouteImport } from './routes/_authenticated/relatorios.personalizados'
import { Route as AuthenticatedRelatoriosPainelGeralRouteImport } from './routes/_authenticated/relatorios.painel-geral'
import { Route as AuthenticatedRelatoriosOperacionaisRouteImport } from './routes/_authenticated/relatorios.operacionais'
import { Route as AuthenticatedRelatoriosGerencialRouteImport } from './routes/_authenticated/relatorios.gerencial'
import { Route as AuthenticatedRelatoriosFinanceirosRouteImport } from './routes/_authenticated/relatorios.financeiros'
import { Route as AuthenticatedRelatoriosExportacoesRouteImport } from './routes/_authenticated/relatorios.exportacoes'
import { Route as AuthenticatedRelatoriosDemandasRouteImport } from './routes/_authenticated/relatorios.demandas'
import { Route as AuthenticatedRelatoriosCrmRouteImport } from './routes/_authenticated/relatorios.crm'
import { Route as AuthenticatedRelatoriosConsolidadoRouteImport } from './routes/_authenticated/relatorios.consolidado'
import { Route as AuthenticatedRelatoriosComissoesRouteImport } from './routes/_authenticated/relatorios.comissoes'
import { Route as AuthenticatedRelatoriosComerciaisRouteImport } from './routes/_authenticated/relatorios.comerciais'
import { Route as AuthenticatedRelatoriosClientesRouteImport } from './routes/_authenticated/relatorios.clientes'
import { Route as AuthenticatedRelatoriosAppClienteRouteImport } from './routes/_authenticated/relatorios.app-cliente'
import { Route as AuthenticatedOperacionalTarefasRouteImport } from './routes/_authenticated/operacional.tarefas'
import { Route as AuthenticatedOperacionalSimulacoesRouteImport } from './routes/_authenticated/operacional.simulacoes'
import { Route as AuthenticatedOperacionalPropostasRouteImport } from './routes/_authenticated/operacional.propostas'
import { Route as AuthenticatedOperacionalPainelRouteImport } from './routes/_authenticated/operacional.painel'
import { Route as AuthenticatedOperacionalDemandasRouteImport } from './routes/_authenticated/operacional.demandas'
import { Route as AuthenticatedOperacionalChatsRouteImport } from './routes/_authenticated/operacional.chats'
import { Route as AuthenticatedFormulariosBancoRouteImport } from './routes/_authenticated/formularios.$banco'
import { Route as AuthenticatedFinanceiroPainelRouteImport } from './routes/_authenticated/financeiro.painel'
import { Route as AuthenticatedFinanceiroFluxoDeCaixaRouteImport } from './routes/_authenticated/financeiro.fluxo-de-caixa'
import { Route as AuthenticatedFinanceiroContasAReceberRouteImport } from './routes/_authenticated/financeiro.contas-a-receber'
import { Route as AuthenticatedFinanceiroContasAPagarRouteImport } from './routes/_authenticated/financeiro.contas-a-pagar'
import { Route as AuthenticatedFinanceiroConfiguracoesRouteImport } from './routes/_authenticated/financeiro.configuracoes'
import { Route as AuthenticatedFinanceiroComissoesUsuarioRouteImport } from './routes/_authenticated/financeiro.comissoes-usuario'
import { Route as AuthenticatedFinanceiroComissoesRouteImport } from './routes/_authenticated/financeiro.comissoes'
import { Route as AuthenticatedCrmScanIaRouteImport } from './routes/_authenticated/crm.scan-ia'
import { Route as AuthenticatedCrmParceirosRouteImport } from './routes/_authenticated/crm.parceiros'
import { Route as AuthenticatedCrmPainelRouteImport } from './routes/_authenticated/crm.painel'
import { Route as AuthenticatedCrmDocumentosRouteImport } from './routes/_authenticated/crm.documentos'
import { Route as AuthenticatedCrmClientesRouteImport } from './routes/_authenticated/crm.clientes'
import { Route as AuthenticatedCrmChatRouteImport } from './routes/_authenticated/crm.chat'
import { Route as AuthenticatedContaSegurancaRouteImport } from './routes/_authenticated/conta.seguranca'
import { Route as AuthenticatedContaPerfilRouteImport } from './routes/_authenticated/conta.perfil'
import { Route as AuthenticatedContaNotificacoesRouteImport } from './routes/_authenticated/conta.notificacoes'
import { Route as AuthenticatedAdminRegrasModulosRouteImport } from './routes/_authenticated/admin.regras-modulos'
import { Route as AuthenticatedAdminPessoasRouteImport } from './routes/_authenticated/admin.pessoas'
import { Route as AuthenticatedAdminParametrosRouteImport } from './routes/_authenticated/admin.parametros'
import { Route as AuthenticatedAdminNotificacoesRouteImport } from './routes/_authenticated/admin.notificacoes'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedAdminComprasRouteImport } from './routes/_authenticated/admin.compras'
import { Route as AuthenticatedAdminBancosRouteImport } from './routes/_authenticated/admin.bancos'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin.backup'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminApisIaRouteImport } from './routes/_authenticated/admin.apis-ia'
import { Route as AuthenticatedOperacionalTarefasKanbanRouteImport } from './routes/_authenticated/operacional.tarefas_.kanban'
import { Route as AuthenticatedOperacionalTarefasCalendarioRouteImport } from './routes/_authenticated/operacional.tarefas_.calendario'
import { Route as AuthenticatedOperacionalSimulacoesNovaRouteImport } from './routes/_authenticated/operacional.simulacoes_.nova'
import { Route as AuthenticatedOperacionalSimulacoesCompletaRouteImport } from './routes/_authenticated/operacional.simulacoes_.completa'
import { Route as AuthenticatedOperacionalSimulacoesIdRouteImport } from './routes/_authenticated/operacional.simulacoes_.$id'
import { Route as AuthenticatedOperacionalPropostasNovaRouteImport } from './routes/_authenticated/operacional.propostas_.nova'
import { Route as AuthenticatedOperacionalPropostasKanbanRouteImport } from './routes/_authenticated/operacional.propostas_.kanban'
import { Route as AuthenticatedOperacionalPropostasEnviarRouteImport } from './routes/_authenticated/operacional.propostas_.enviar'
import { Route as AuthenticatedOperacionalPropostasIdRouteImport } from './routes/_authenticated/operacional.propostas_.$id'
import { Route as AuthenticatedOperacionalDemandasKanbanRouteImport } from './routes/_authenticated/operacional.demandas_.kanban'
import { Route as AuthenticatedOperacionalDemandasIdRouteImport } from './routes/_authenticated/operacional.demandas_.$id'
import { Route as AuthenticatedCrmScanIaIdRouteImport } from './routes/_authenticated/crm.scan-ia_.$id'
import { Route as AuthenticatedCrmClientesNovoRouteImport } from './routes/_authenticated/crm.clientes_.novo'
import { Route as AuthenticatedCrmClientesIdRouteImport } from './routes/_authenticated/crm.clientes_.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroRoute = ParceiroRouteImport.update({
  id: '/parceiro',
  path: '/parceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteConsentimentoRoute = ClienteConsentimentoRouteImport.update({
  id: '/cliente-consentimento',
  path: '/cliente-consentimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroSimulacoesRoute = ParceiroSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroPropostasRoute = ParceiroPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroDocumentosRoute = ParceiroDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroComissoesRoute = ParceiroComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => ParceiroRoute,
} as any)
const ParceiroClientesRoute = ParceiroClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => ParceiroRoute,
} as any)
const ClienteVisaoGeralRoute = ClienteVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteLogoutRoute = ClienteLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteChatRoute = ClienteChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteAcompanharMinhaPropostaRoute =
  ClienteAcompanharMinhaPropostaRouteImport.update({
    id: '/acompanhar-minha-proposta',
    path: '/acompanhar-minha-proposta',
    getParentRoute: () => ClienteRoute,
  } as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParceiroInicioRoute =
  AuthenticatedParceiroInicioRouteImport.update({
    id: '/parceiro-inicio',
    path: '/parceiro-inicio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatriculasRoute = AuthenticatedMatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormulariosRoute =
  AuthenticatedFormulariosRouteImport.update({
    id: '/formularios',
    path: '/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedFormulariosIndexRoute =
  AuthenticatedFormulariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFormulariosRoute,
  } as any)
const ApiPublicSyncPropostasRoute = ApiPublicSyncPropostasRouteImport.update({
  id: '/api/public/sync-propostas',
  path: '/api/public/sync-propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisaoGeralPainelRoute =
  AuthenticatedVisaoGeralPainelRouteImport.update({
    id: '/visao-geral/painel',
    path: '/visao-geral/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosTarefasRoute =
  AuthenticatedRelatoriosTarefasRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosSimulacoesRoute =
  AuthenticatedRelatoriosSimulacoesRouteImport.update({
    id: '/simulacoes',
    path: '/simulacoes',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosPropostasRoute =
  AuthenticatedRelatoriosPropostasRouteImport.update({
    id: '/propostas',
    path: '/propostas',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosPersonalizadosRoute =
  AuthenticatedRelatoriosPersonalizadosRouteImport.update({
    id: '/personalizados',
    path: '/personalizados',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosPainelGeralRoute =
  AuthenticatedRelatoriosPainelGeralRouteImport.update({
    id: '/painel-geral',
    path: '/painel-geral',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosOperacionaisRoute =
  AuthenticatedRelatoriosOperacionaisRouteImport.update({
    id: '/operacionais',
    path: '/operacionais',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosGerencialRoute =
  AuthenticatedRelatoriosGerencialRouteImport.update({
    id: '/gerencial',
    path: '/gerencial',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosFinanceirosRoute =
  AuthenticatedRelatoriosFinanceirosRouteImport.update({
    id: '/financeiros',
    path: '/financeiros',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosExportacoesRoute =
  AuthenticatedRelatoriosExportacoesRouteImport.update({
    id: '/exportacoes',
    path: '/exportacoes',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosDemandasRoute =
  AuthenticatedRelatoriosDemandasRouteImport.update({
    id: '/demandas',
    path: '/demandas',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosCrmRoute =
  AuthenticatedRelatoriosCrmRouteImport.update({
    id: '/crm',
    path: '/crm',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosConsolidadoRoute =
  AuthenticatedRelatoriosConsolidadoRouteImport.update({
    id: '/consolidado',
    path: '/consolidado',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosComissoesRoute =
  AuthenticatedRelatoriosComissoesRouteImport.update({
    id: '/comissoes',
    path: '/comissoes',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosComerciaisRoute =
  AuthenticatedRelatoriosComerciaisRouteImport.update({
    id: '/comerciais',
    path: '/comerciais',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosClientesRoute =
  AuthenticatedRelatoriosClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosAppClienteRoute =
  AuthenticatedRelatoriosAppClienteRouteImport.update({
    id: '/app-cliente',
    path: '/app-cliente',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedOperacionalTarefasRoute =
  AuthenticatedOperacionalTarefasRouteImport.update({
    id: '/operacional/tarefas',
    path: '/operacional/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalSimulacoesRoute =
  AuthenticatedOperacionalSimulacoesRouteImport.update({
    id: '/operacional/simulacoes',
    path: '/operacional/simulacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPropostasRoute =
  AuthenticatedOperacionalPropostasRouteImport.update({
    id: '/operacional/propostas',
    path: '/operacional/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPainelRoute =
  AuthenticatedOperacionalPainelRouteImport.update({
    id: '/operacional/painel',
    path: '/operacional/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalDemandasRoute =
  AuthenticatedOperacionalDemandasRouteImport.update({
    id: '/operacional/demandas',
    path: '/operacional/demandas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalChatsRoute =
  AuthenticatedOperacionalChatsRouteImport.update({
    id: '/operacional/chats',
    path: '/operacional/chats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormulariosBancoRoute =
  AuthenticatedFormulariosBancoRouteImport.update({
    id: '/$banco',
    path: '/$banco',
    getParentRoute: () => AuthenticatedFormulariosRoute,
  } as any)
const AuthenticatedFinanceiroPainelRoute =
  AuthenticatedFinanceiroPainelRouteImport.update({
    id: '/financeiro/painel',
    path: '/financeiro/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoDeCaixaRoute =
  AuthenticatedFinanceiroFluxoDeCaixaRouteImport.update({
    id: '/financeiro/fluxo-de-caixa',
    path: '/financeiro/fluxo-de-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasAReceberRoute =
  AuthenticatedFinanceiroContasAReceberRouteImport.update({
    id: '/financeiro/contas-a-receber',
    path: '/financeiro/contas-a-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasAPagarRoute =
  AuthenticatedFinanceiroContasAPagarRouteImport.update({
    id: '/financeiro/contas-a-pagar',
    path: '/financeiro/contas-a-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConfiguracoesRoute =
  AuthenticatedFinanceiroConfiguracoesRouteImport.update({
    id: '/financeiro/configuracoes',
    path: '/financeiro/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroComissoesUsuarioRoute =
  AuthenticatedFinanceiroComissoesUsuarioRouteImport.update({
    id: '/financeiro/comissoes-usuario',
    path: '/financeiro/comissoes-usuario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroComissoesRoute =
  AuthenticatedFinanceiroComissoesRouteImport.update({
    id: '/financeiro/comissoes',
    path: '/financeiro/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmScanIaRoute = AuthenticatedCrmScanIaRouteImport.update({
  id: '/crm/scan-ia',
  path: '/crm/scan-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmParceirosRoute =
  AuthenticatedCrmParceirosRouteImport.update({
    id: '/crm/parceiros',
    path: '/crm/parceiros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmPainelRoute = AuthenticatedCrmPainelRouteImport.update({
  id: '/crm/painel',
  path: '/crm/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmDocumentosRoute =
  AuthenticatedCrmDocumentosRouteImport.update({
    id: '/crm/documentos',
    path: '/crm/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientesRoute =
  AuthenticatedCrmClientesRouteImport.update({
    id: '/crm/clientes',
    path: '/crm/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmChatRoute = AuthenticatedCrmChatRouteImport.update({
  id: '/crm/chat',
  path: '/crm/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaSegurancaRoute =
  AuthenticatedContaSegurancaRouteImport.update({
    id: '/conta/seguranca',
    path: '/conta/seguranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaPerfilRoute =
  AuthenticatedContaPerfilRouteImport.update({
    id: '/conta/perfil',
    path: '/conta/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaNotificacoesRoute =
  AuthenticatedContaNotificacoesRouteImport.update({
    id: '/conta/notificacoes',
    path: '/conta/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRegrasModulosRoute =
  AuthenticatedAdminRegrasModulosRouteImport.update({
    id: '/admin/regras-modulos',
    path: '/admin/regras-modulos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPessoasRoute =
  AuthenticatedAdminPessoasRouteImport.update({
    id: '/admin/pessoas',
    path: '/admin/pessoas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminParametrosRoute =
  AuthenticatedAdminParametrosRouteImport.update({
    id: '/admin/parametros',
    path: '/admin/parametros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificacoesRoute =
  AuthenticatedAdminNotificacoesRouteImport.update({
    id: '/admin/notificacoes',
    path: '/admin/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/admin/integracoes',
    path: '/admin/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComprasRoute =
  AuthenticatedAdminComprasRouteImport.update({
    id: '/admin/compras',
    path: '/admin/compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBancosRoute =
  AuthenticatedAdminBancosRouteImport.update({
    id: '/admin/bancos',
    path: '/admin/bancos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/admin/backup',
    path: '/admin/backup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApisIaRoute =
  AuthenticatedAdminApisIaRouteImport.update({
    id: '/admin/apis-ia',
    path: '/admin/apis-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalTarefasKanbanRoute =
  AuthenticatedOperacionalTarefasKanbanRouteImport.update({
    id: '/operacional/tarefas_/kanban',
    path: '/operacional/tarefas/kanban',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalTarefasCalendarioRoute =
  AuthenticatedOperacionalTarefasCalendarioRouteImport.update({
    id: '/operacional/tarefas_/calendario',
    path: '/operacional/tarefas/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalSimulacoesNovaRoute =
  AuthenticatedOperacionalSimulacoesNovaRouteImport.update({
    id: '/operacional/simulacoes_/nova',
    path: '/operacional/simulacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalSimulacoesCompletaRoute =
  AuthenticatedOperacionalSimulacoesCompletaRouteImport.update({
    id: '/operacional/simulacoes_/completa',
    path: '/operacional/simulacoes/completa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalSimulacoesIdRoute =
  AuthenticatedOperacionalSimulacoesIdRouteImport.update({
    id: '/operacional/simulacoes_/$id',
    path: '/operacional/simulacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPropostasNovaRoute =
  AuthenticatedOperacionalPropostasNovaRouteImport.update({
    id: '/operacional/propostas_/nova',
    path: '/operacional/propostas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPropostasKanbanRoute =
  AuthenticatedOperacionalPropostasKanbanRouteImport.update({
    id: '/operacional/propostas_/kanban',
    path: '/operacional/propostas/kanban',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPropostasEnviarRoute =
  AuthenticatedOperacionalPropostasEnviarRouteImport.update({
    id: '/operacional/propostas_/enviar',
    path: '/operacional/propostas/enviar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalPropostasIdRoute =
  AuthenticatedOperacionalPropostasIdRouteImport.update({
    id: '/operacional/propostas_/$id',
    path: '/operacional/propostas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalDemandasKanbanRoute =
  AuthenticatedOperacionalDemandasKanbanRouteImport.update({
    id: '/operacional/demandas_/kanban',
    path: '/operacional/demandas/kanban',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionalDemandasIdRoute =
  AuthenticatedOperacionalDemandasIdRouteImport.update({
    id: '/operacional/demandas_/$id',
    path: '/operacional/demandas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmScanIaIdRoute =
  AuthenticatedCrmScanIaIdRouteImport.update({
    id: '/crm/scan-ia_/$id',
    path: '/crm/scan-ia/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientesNovoRoute =
  AuthenticatedCrmClientesNovoRouteImport.update({
    id: '/crm/clientes_/novo',
    path: '/crm/clientes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientesIdRoute =
  AuthenticatedCrmClientesIdRouteImport.update({
    id: '/crm/clientes_/$id',
    path: '/crm/clientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente-consentimento': typeof ClienteConsentimentoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/formularios': typeof AuthenticatedFormulariosRouteWithChildren
  '/links': typeof AuthenticatedLinksRoute
  '/matriculas': typeof AuthenticatedMatriculasRoute
  '/parceiro-inicio': typeof AuthenticatedParceiroInicioRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/rh': typeof AuthenticatedRhRoute
  '/cliente/acompanhar-minha-proposta': typeof ClienteAcompanharMinhaPropostaRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/logout': typeof ClienteLogoutRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/visao-geral': typeof ClienteVisaoGeralRoute
  '/parceiro/clientes': typeof ParceiroClientesRoute
  '/parceiro/comissoes': typeof ParceiroComissoesRoute
  '/parceiro/documentos': typeof ParceiroDocumentosRoute
  '/parceiro/propostas': typeof ParceiroPropostasRoute
  '/parceiro/simulacoes': typeof ParceiroSimulacoesRoute
  '/admin/apis-ia': typeof AuthenticatedAdminApisIaRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/bancos': typeof AuthenticatedAdminBancosRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/pessoas': typeof AuthenticatedAdminPessoasRoute
  '/admin/regras-modulos': typeof AuthenticatedAdminRegrasModulosRoute
  '/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/conta/perfil': typeof AuthenticatedContaPerfilRoute
  '/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/crm/chat': typeof AuthenticatedCrmChatRoute
  '/crm/clientes': typeof AuthenticatedCrmClientesRoute
  '/crm/documentos': typeof AuthenticatedCrmDocumentosRoute
  '/crm/painel': typeof AuthenticatedCrmPainelRoute
  '/crm/parceiros': typeof AuthenticatedCrmParceirosRoute
  '/crm/scan-ia': typeof AuthenticatedCrmScanIaRoute
  '/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/financeiro/comissoes-usuario': typeof AuthenticatedFinanceiroComissoesUsuarioRoute
  '/financeiro/configuracoes': typeof AuthenticatedFinanceiroConfiguracoesRoute
  '/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/financeiro/painel': typeof AuthenticatedFinanceiroPainelRoute
  '/formularios/$banco': typeof AuthenticatedFormulariosBancoRoute
  '/operacional/chats': typeof AuthenticatedOperacionalChatsRoute
  '/operacional/demandas': typeof AuthenticatedOperacionalDemandasRoute
  '/operacional/painel': typeof AuthenticatedOperacionalPainelRoute
  '/operacional/propostas': typeof AuthenticatedOperacionalPropostasRoute
  '/operacional/simulacoes': typeof AuthenticatedOperacionalSimulacoesRoute
  '/operacional/tarefas': typeof AuthenticatedOperacionalTarefasRoute
  '/relatorios/app-cliente': typeof AuthenticatedRelatoriosAppClienteRoute
  '/relatorios/clientes': typeof AuthenticatedRelatoriosClientesRoute
  '/relatorios/comerciais': typeof AuthenticatedRelatoriosComerciaisRoute
  '/relatorios/comissoes': typeof AuthenticatedRelatoriosComissoesRoute
  '/relatorios/consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/relatorios/crm': typeof AuthenticatedRelatoriosCrmRoute
  '/relatorios/demandas': typeof AuthenticatedRelatoriosDemandasRoute
  '/relatorios/exportacoes': typeof AuthenticatedRelatoriosExportacoesRoute
  '/relatorios/financeiros': typeof AuthenticatedRelatoriosFinanceirosRoute
  '/relatorios/gerencial': typeof AuthenticatedRelatoriosGerencialRoute
  '/relatorios/operacionais': typeof AuthenticatedRelatoriosOperacionaisRoute
  '/relatorios/painel-geral': typeof AuthenticatedRelatoriosPainelGeralRoute
  '/relatorios/personalizados': typeof AuthenticatedRelatoriosPersonalizadosRoute
  '/relatorios/propostas': typeof AuthenticatedRelatoriosPropostasRoute
  '/relatorios/simulacoes': typeof AuthenticatedRelatoriosSimulacoesRoute
  '/relatorios/tarefas': typeof AuthenticatedRelatoriosTarefasRoute
  '/visao-geral/painel': typeof AuthenticatedVisaoGeralPainelRoute
  '/api/public/sync-propostas': typeof ApiPublicSyncPropostasRoute
  '/formularios/': typeof AuthenticatedFormulariosIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/crm/clientes/$id': typeof AuthenticatedCrmClientesIdRoute
  '/crm/clientes/novo': typeof AuthenticatedCrmClientesNovoRoute
  '/crm/scan-ia/$id': typeof AuthenticatedCrmScanIaIdRoute
  '/operacional/demandas/$id': typeof AuthenticatedOperacionalDemandasIdRoute
  '/operacional/demandas/kanban': typeof AuthenticatedOperacionalDemandasKanbanRoute
  '/operacional/propostas/$id': typeof AuthenticatedOperacionalPropostasIdRoute
  '/operacional/propostas/enviar': typeof AuthenticatedOperacionalPropostasEnviarRoute
  '/operacional/propostas/kanban': typeof AuthenticatedOperacionalPropostasKanbanRoute
  '/operacional/propostas/nova': typeof AuthenticatedOperacionalPropostasNovaRoute
  '/operacional/simulacoes/$id': typeof AuthenticatedOperacionalSimulacoesIdRoute
  '/operacional/simulacoes/completa': typeof AuthenticatedOperacionalSimulacoesCompletaRoute
  '/operacional/simulacoes/nova': typeof AuthenticatedOperacionalSimulacoesNovaRoute
  '/operacional/tarefas/calendario': typeof AuthenticatedOperacionalTarefasCalendarioRoute
  '/operacional/tarefas/kanban': typeof AuthenticatedOperacionalTarefasKanbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente-consentimento': typeof ClienteConsentimentoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/links': typeof AuthenticatedLinksRoute
  '/matriculas': typeof AuthenticatedMatriculasRoute
  '/parceiro-inicio': typeof AuthenticatedParceiroInicioRoute
  '/rh': typeof AuthenticatedRhRoute
  '/cliente/acompanhar-minha-proposta': typeof ClienteAcompanharMinhaPropostaRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/logout': typeof ClienteLogoutRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/visao-geral': typeof ClienteVisaoGeralRoute
  '/parceiro/clientes': typeof ParceiroClientesRoute
  '/parceiro/comissoes': typeof ParceiroComissoesRoute
  '/parceiro/documentos': typeof ParceiroDocumentosRoute
  '/parceiro/propostas': typeof ParceiroPropostasRoute
  '/parceiro/simulacoes': typeof ParceiroSimulacoesRoute
  '/admin/apis-ia': typeof AuthenticatedAdminApisIaRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/bancos': typeof AuthenticatedAdminBancosRoute
  '/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/admin/pessoas': typeof AuthenticatedAdminPessoasRoute
  '/admin/regras-modulos': typeof AuthenticatedAdminRegrasModulosRoute
  '/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/conta/perfil': typeof AuthenticatedContaPerfilRoute
  '/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/crm/chat': typeof AuthenticatedCrmChatRoute
  '/crm/clientes': typeof AuthenticatedCrmClientesRoute
  '/crm/documentos': typeof AuthenticatedCrmDocumentosRoute
  '/crm/painel': typeof AuthenticatedCrmPainelRoute
  '/crm/parceiros': typeof AuthenticatedCrmParceirosRoute
  '/crm/scan-ia': typeof AuthenticatedCrmScanIaRoute
  '/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/financeiro/comissoes-usuario': typeof AuthenticatedFinanceiroComissoesUsuarioRoute
  '/financeiro/configuracoes': typeof AuthenticatedFinanceiroConfiguracoesRoute
  '/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/financeiro/painel': typeof AuthenticatedFinanceiroPainelRoute
  '/formularios/$banco': typeof AuthenticatedFormulariosBancoRoute
  '/operacional/chats': typeof AuthenticatedOperacionalChatsRoute
  '/operacional/demandas': typeof AuthenticatedOperacionalDemandasRoute
  '/operacional/painel': typeof AuthenticatedOperacionalPainelRoute
  '/operacional/propostas': typeof AuthenticatedOperacionalPropostasRoute
  '/operacional/simulacoes': typeof AuthenticatedOperacionalSimulacoesRoute
  '/operacional/tarefas': typeof AuthenticatedOperacionalTarefasRoute
  '/relatorios/app-cliente': typeof AuthenticatedRelatoriosAppClienteRoute
  '/relatorios/clientes': typeof AuthenticatedRelatoriosClientesRoute
  '/relatorios/comerciais': typeof AuthenticatedRelatoriosComerciaisRoute
  '/relatorios/comissoes': typeof AuthenticatedRelatoriosComissoesRoute
  '/relatorios/consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/relatorios/crm': typeof AuthenticatedRelatoriosCrmRoute
  '/relatorios/demandas': typeof AuthenticatedRelatoriosDemandasRoute
  '/relatorios/exportacoes': typeof AuthenticatedRelatoriosExportacoesRoute
  '/relatorios/financeiros': typeof AuthenticatedRelatoriosFinanceirosRoute
  '/relatorios/gerencial': typeof AuthenticatedRelatoriosGerencialRoute
  '/relatorios/operacionais': typeof AuthenticatedRelatoriosOperacionaisRoute
  '/relatorios/painel-geral': typeof AuthenticatedRelatoriosPainelGeralRoute
  '/relatorios/personalizados': typeof AuthenticatedRelatoriosPersonalizadosRoute
  '/relatorios/propostas': typeof AuthenticatedRelatoriosPropostasRoute
  '/relatorios/simulacoes': typeof AuthenticatedRelatoriosSimulacoesRoute
  '/relatorios/tarefas': typeof AuthenticatedRelatoriosTarefasRoute
  '/visao-geral/painel': typeof AuthenticatedVisaoGeralPainelRoute
  '/api/public/sync-propostas': typeof ApiPublicSyncPropostasRoute
  '/formularios': typeof AuthenticatedFormulariosIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/crm/clientes/$id': typeof AuthenticatedCrmClientesIdRoute
  '/crm/clientes/novo': typeof AuthenticatedCrmClientesNovoRoute
  '/crm/scan-ia/$id': typeof AuthenticatedCrmScanIaIdRoute
  '/operacional/demandas/$id': typeof AuthenticatedOperacionalDemandasIdRoute
  '/operacional/demandas/kanban': typeof AuthenticatedOperacionalDemandasKanbanRoute
  '/operacional/propostas/$id': typeof AuthenticatedOperacionalPropostasIdRoute
  '/operacional/propostas/enviar': typeof AuthenticatedOperacionalPropostasEnviarRoute
  '/operacional/propostas/kanban': typeof AuthenticatedOperacionalPropostasKanbanRoute
  '/operacional/propostas/nova': typeof AuthenticatedOperacionalPropostasNovaRoute
  '/operacional/simulacoes/$id': typeof AuthenticatedOperacionalSimulacoesIdRoute
  '/operacional/simulacoes/completa': typeof AuthenticatedOperacionalSimulacoesCompletaRoute
  '/operacional/simulacoes/nova': typeof AuthenticatedOperacionalSimulacoesNovaRoute
  '/operacional/tarefas/calendario': typeof AuthenticatedOperacionalTarefasCalendarioRoute
  '/operacional/tarefas/kanban': typeof AuthenticatedOperacionalTarefasKanbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente-consentimento': typeof ClienteConsentimentoRoute
  '/parceiro': typeof ParceiroRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/portal': typeof PortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/formularios': typeof AuthenticatedFormulariosRouteWithChildren
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/matriculas': typeof AuthenticatedMatriculasRoute
  '/_authenticated/parceiro-inicio': typeof AuthenticatedParceiroInicioRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/_authenticated/rh': typeof AuthenticatedRhRoute
  '/cliente/acompanhar-minha-proposta': typeof ClienteAcompanharMinhaPropostaRoute
  '/cliente/chat': typeof ClienteChatRoute
  '/cliente/logout': typeof ClienteLogoutRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/visao-geral': typeof ClienteVisaoGeralRoute
  '/parceiro/clientes': typeof ParceiroClientesRoute
  '/parceiro/comissoes': typeof ParceiroComissoesRoute
  '/parceiro/documentos': typeof ParceiroDocumentosRoute
  '/parceiro/propostas': typeof ParceiroPropostasRoute
  '/parceiro/simulacoes': typeof ParceiroSimulacoesRoute
  '/_authenticated/admin/apis-ia': typeof AuthenticatedAdminApisIaRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/bancos': typeof AuthenticatedAdminBancosRoute
  '/_authenticated/admin/compras': typeof AuthenticatedAdminComprasRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/notificacoes': typeof AuthenticatedAdminNotificacoesRoute
  '/_authenticated/admin/parametros': typeof AuthenticatedAdminParametrosRoute
  '/_authenticated/admin/pessoas': typeof AuthenticatedAdminPessoasRoute
  '/_authenticated/admin/regras-modulos': typeof AuthenticatedAdminRegrasModulosRoute
  '/_authenticated/conta/notificacoes': typeof AuthenticatedContaNotificacoesRoute
  '/_authenticated/conta/perfil': typeof AuthenticatedContaPerfilRoute
  '/_authenticated/conta/seguranca': typeof AuthenticatedContaSegurancaRoute
  '/_authenticated/crm/chat': typeof AuthenticatedCrmChatRoute
  '/_authenticated/crm/clientes': typeof AuthenticatedCrmClientesRoute
  '/_authenticated/crm/documentos': typeof AuthenticatedCrmDocumentosRoute
  '/_authenticated/crm/painel': typeof AuthenticatedCrmPainelRoute
  '/_authenticated/crm/parceiros': typeof AuthenticatedCrmParceirosRoute
  '/_authenticated/crm/scan-ia': typeof AuthenticatedCrmScanIaRoute
  '/_authenticated/financeiro/comissoes': typeof AuthenticatedFinanceiroComissoesRoute
  '/_authenticated/financeiro/comissoes-usuario': typeof AuthenticatedFinanceiroComissoesUsuarioRoute
  '/_authenticated/financeiro/configuracoes': typeof AuthenticatedFinanceiroConfiguracoesRoute
  '/_authenticated/financeiro/contas-a-pagar': typeof AuthenticatedFinanceiroContasAPagarRoute
  '/_authenticated/financeiro/contas-a-receber': typeof AuthenticatedFinanceiroContasAReceberRoute
  '/_authenticated/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/_authenticated/financeiro/painel': typeof AuthenticatedFinanceiroPainelRoute
  '/_authenticated/formularios/$banco': typeof AuthenticatedFormulariosBancoRoute
  '/_authenticated/operacional/chats': typeof AuthenticatedOperacionalChatsRoute
  '/_authenticated/operacional/demandas': typeof AuthenticatedOperacionalDemandasRoute
  '/_authenticated/operacional/painel': typeof AuthenticatedOperacionalPainelRoute
  '/_authenticated/operacional/propostas': typeof AuthenticatedOperacionalPropostasRoute
  '/_authenticated/operacional/simulacoes': typeof AuthenticatedOperacionalSimulacoesRoute
  '/_authenticated/operacional/tarefas': typeof AuthenticatedOperacionalTarefasRoute
  '/_authenticated/relatorios/app-cliente': typeof AuthenticatedRelatoriosAppClienteRoute
  '/_authenticated/relatorios/clientes': typeof AuthenticatedRelatoriosClientesRoute
  '/_authenticated/relatorios/comerciais': typeof AuthenticatedRelatoriosComerciaisRoute
  '/_authenticated/relatorios/comissoes': typeof AuthenticatedRelatoriosComissoesRoute
  '/_authenticated/relatorios/consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/_authenticated/relatorios/crm': typeof AuthenticatedRelatoriosCrmRoute
  '/_authenticated/relatorios/demandas': typeof AuthenticatedRelatoriosDemandasRoute
  '/_authenticated/relatorios/exportacoes': typeof AuthenticatedRelatoriosExportacoesRoute
  '/_authenticated/relatorios/financeiros': typeof AuthenticatedRelatoriosFinanceirosRoute
  '/_authenticated/relatorios/gerencial': typeof AuthenticatedRelatoriosGerencialRoute
  '/_authenticated/relatorios/operacionais': typeof AuthenticatedRelatoriosOperacionaisRoute
  '/_authenticated/relatorios/painel-geral': typeof AuthenticatedRelatoriosPainelGeralRoute
  '/_authenticated/relatorios/personalizados': typeof AuthenticatedRelatoriosPersonalizadosRoute
  '/_authenticated/relatorios/propostas': typeof AuthenticatedRelatoriosPropostasRoute
  '/_authenticated/relatorios/simulacoes': typeof AuthenticatedRelatoriosSimulacoesRoute
  '/_authenticated/relatorios/tarefas': typeof AuthenticatedRelatoriosTarefasRoute
  '/_authenticated/visao-geral/painel': typeof AuthenticatedVisaoGeralPainelRoute
  '/api/public/sync-propostas': typeof ApiPublicSyncPropostasRoute
  '/_authenticated/formularios/': typeof AuthenticatedFormulariosIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/crm/clientes_/$id': typeof AuthenticatedCrmClientesIdRoute
  '/_authenticated/crm/clientes_/novo': typeof AuthenticatedCrmClientesNovoRoute
  '/_authenticated/crm/scan-ia_/$id': typeof AuthenticatedCrmScanIaIdRoute
  '/_authenticated/operacional/demandas_/$id': typeof AuthenticatedOperacionalDemandasIdRoute
  '/_authenticated/operacional/demandas_/kanban': typeof AuthenticatedOperacionalDemandasKanbanRoute
  '/_authenticated/operacional/propostas_/$id': typeof AuthenticatedOperacionalPropostasIdRoute
  '/_authenticated/operacional/propostas_/enviar': typeof AuthenticatedOperacionalPropostasEnviarRoute
  '/_authenticated/operacional/propostas_/kanban': typeof AuthenticatedOperacionalPropostasKanbanRoute
  '/_authenticated/operacional/propostas_/nova': typeof AuthenticatedOperacionalPropostasNovaRoute
  '/_authenticated/operacional/simulacoes_/$id': typeof AuthenticatedOperacionalSimulacoesIdRoute
  '/_authenticated/operacional/simulacoes_/completa': typeof AuthenticatedOperacionalSimulacoesCompletaRoute
  '/_authenticated/operacional/simulacoes_/nova': typeof AuthenticatedOperacionalSimulacoesNovaRoute
  '/_authenticated/operacional/tarefas_/calendario': typeof AuthenticatedOperacionalTarefasCalendarioRoute
  '/_authenticated/operacional/tarefas_/kanban': typeof AuthenticatedOperacionalTarefasKanbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cliente'
    | '/cliente-consentimento'
    | '/parceiro'
    | '/politica-de-privacidade'
    | '/portal'
    | '/dashboard'
    | '/documentos'
    | '/formularios'
    | '/links'
    | '/matriculas'
    | '/parceiro-inicio'
    | '/relatorios'
    | '/rh'
    | '/cliente/acompanhar-minha-proposta'
    | '/cliente/chat'
    | '/cliente/logout'
    | '/cliente/perfil'
    | '/cliente/visao-geral'
    | '/parceiro/clientes'
    | '/parceiro/comissoes'
    | '/parceiro/documentos'
    | '/parceiro/propostas'
    | '/parceiro/simulacoes'
    | '/admin/apis-ia'
    | '/admin/auditoria'
    | '/admin/backup'
    | '/admin/bancos'
    | '/admin/compras'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/parametros'
    | '/admin/pessoas'
    | '/admin/regras-modulos'
    | '/conta/notificacoes'
    | '/conta/perfil'
    | '/conta/seguranca'
    | '/crm/chat'
    | '/crm/clientes'
    | '/crm/documentos'
    | '/crm/painel'
    | '/crm/parceiros'
    | '/crm/scan-ia'
    | '/financeiro/comissoes'
    | '/financeiro/comissoes-usuario'
    | '/financeiro/configuracoes'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/fluxo-de-caixa'
    | '/financeiro/painel'
    | '/formularios/$banco'
    | '/operacional/chats'
    | '/operacional/demandas'
    | '/operacional/painel'
    | '/operacional/propostas'
    | '/operacional/simulacoes'
    | '/operacional/tarefas'
    | '/relatorios/app-cliente'
    | '/relatorios/clientes'
    | '/relatorios/comerciais'
    | '/relatorios/comissoes'
    | '/relatorios/consolidado'
    | '/relatorios/crm'
    | '/relatorios/demandas'
    | '/relatorios/exportacoes'
    | '/relatorios/financeiros'
    | '/relatorios/gerencial'
    | '/relatorios/operacionais'
    | '/relatorios/painel-geral'
    | '/relatorios/personalizados'
    | '/relatorios/propostas'
    | '/relatorios/simulacoes'
    | '/relatorios/tarefas'
    | '/visao-geral/painel'
    | '/api/public/sync-propostas'
    | '/formularios/'
    | '/relatorios/'
    | '/crm/clientes/$id'
    | '/crm/clientes/novo'
    | '/crm/scan-ia/$id'
    | '/operacional/demandas/$id'
    | '/operacional/demandas/kanban'
    | '/operacional/propostas/$id'
    | '/operacional/propostas/enviar'
    | '/operacional/propostas/kanban'
    | '/operacional/propostas/nova'
    | '/operacional/simulacoes/$id'
    | '/operacional/simulacoes/completa'
    | '/operacional/simulacoes/nova'
    | '/operacional/tarefas/calendario'
    | '/operacional/tarefas/kanban'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cliente'
    | '/cliente-consentimento'
    | '/parceiro'
    | '/politica-de-privacidade'
    | '/portal'
    | '/dashboard'
    | '/documentos'
    | '/links'
    | '/matriculas'
    | '/parceiro-inicio'
    | '/rh'
    | '/cliente/acompanhar-minha-proposta'
    | '/cliente/chat'
    | '/cliente/logout'
    | '/cliente/perfil'
    | '/cliente/visao-geral'
    | '/parceiro/clientes'
    | '/parceiro/comissoes'
    | '/parceiro/documentos'
    | '/parceiro/propostas'
    | '/parceiro/simulacoes'
    | '/admin/apis-ia'
    | '/admin/auditoria'
    | '/admin/backup'
    | '/admin/bancos'
    | '/admin/compras'
    | '/admin/integracoes'
    | '/admin/notificacoes'
    | '/admin/parametros'
    | '/admin/pessoas'
    | '/admin/regras-modulos'
    | '/conta/notificacoes'
    | '/conta/perfil'
    | '/conta/seguranca'
    | '/crm/chat'
    | '/crm/clientes'
    | '/crm/documentos'
    | '/crm/painel'
    | '/crm/parceiros'
    | '/crm/scan-ia'
    | '/financeiro/comissoes'
    | '/financeiro/comissoes-usuario'
    | '/financeiro/configuracoes'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/fluxo-de-caixa'
    | '/financeiro/painel'
    | '/formularios/$banco'
    | '/operacional/chats'
    | '/operacional/demandas'
    | '/operacional/painel'
    | '/operacional/propostas'
    | '/operacional/simulacoes'
    | '/operacional/tarefas'
    | '/relatorios/app-cliente'
    | '/relatorios/clientes'
    | '/relatorios/comerciais'
    | '/relatorios/comissoes'
    | '/relatorios/consolidado'
    | '/relatorios/crm'
    | '/relatorios/demandas'
    | '/relatorios/exportacoes'
    | '/relatorios/financeiros'
    | '/relatorios/gerencial'
    | '/relatorios/operacionais'
    | '/relatorios/painel-geral'
    | '/relatorios/personalizados'
    | '/relatorios/propostas'
    | '/relatorios/simulacoes'
    | '/relatorios/tarefas'
    | '/visao-geral/painel'
    | '/api/public/sync-propostas'
    | '/formularios'
    | '/relatorios'
    | '/crm/clientes/$id'
    | '/crm/clientes/novo'
    | '/crm/scan-ia/$id'
    | '/operacional/demandas/$id'
    | '/operacional/demandas/kanban'
    | '/operacional/propostas/$id'
    | '/operacional/propostas/enviar'
    | '/operacional/propostas/kanban'
    | '/operacional/propostas/nova'
    | '/operacional/simulacoes/$id'
    | '/operacional/simulacoes/completa'
    | '/operacional/simulacoes/nova'
    | '/operacional/tarefas/calendario'
    | '/operacional/tarefas/kanban'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cliente'
    | '/cliente-consentimento'
    | '/parceiro'
    | '/politica-de-privacidade'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/formularios'
    | '/_authenticated/links'
    | '/_authenticated/matriculas'
    | '/_authenticated/parceiro-inicio'
    | '/_authenticated/relatorios'
    | '/_authenticated/rh'
    | '/cliente/acompanhar-minha-proposta'
    | '/cliente/chat'
    | '/cliente/logout'
    | '/cliente/perfil'
    | '/cliente/visao-geral'
    | '/parceiro/clientes'
    | '/parceiro/comissoes'
    | '/parceiro/documentos'
    | '/parceiro/propostas'
    | '/parceiro/simulacoes'
    | '/_authenticated/admin/apis-ia'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/bancos'
    | '/_authenticated/admin/compras'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/notificacoes'
    | '/_authenticated/admin/parametros'
    | '/_authenticated/admin/pessoas'
    | '/_authenticated/admin/regras-modulos'
    | '/_authenticated/conta/notificacoes'
    | '/_authenticated/conta/perfil'
    | '/_authenticated/conta/seguranca'
    | '/_authenticated/crm/chat'
    | '/_authenticated/crm/clientes'
    | '/_authenticated/crm/documentos'
    | '/_authenticated/crm/painel'
    | '/_authenticated/crm/parceiros'
    | '/_authenticated/crm/scan-ia'
    | '/_authenticated/financeiro/comissoes'
    | '/_authenticated/financeiro/comissoes-usuario'
    | '/_authenticated/financeiro/configuracoes'
    | '/_authenticated/financeiro/contas-a-pagar'
    | '/_authenticated/financeiro/contas-a-receber'
    | '/_authenticated/financeiro/fluxo-de-caixa'
    | '/_authenticated/financeiro/painel'
    | '/_authenticated/formularios/$banco'
    | '/_authenticated/operacional/chats'
    | '/_authenticated/operacional/demandas'
    | '/_authenticated/operacional/painel'
    | '/_authenticated/operacional/propostas'
    | '/_authenticated/operacional/simulacoes'
    | '/_authenticated/operacional/tarefas'
    | '/_authenticated/relatorios/app-cliente'
    | '/_authenticated/relatorios/clientes'
    | '/_authenticated/relatorios/comerciais'
    | '/_authenticated/relatorios/comissoes'
    | '/_authenticated/relatorios/consolidado'
    | '/_authenticated/relatorios/crm'
    | '/_authenticated/relatorios/demandas'
    | '/_authenticated/relatorios/exportacoes'
    | '/_authenticated/relatorios/financeiros'
    | '/_authenticated/relatorios/gerencial'
    | '/_authenticated/relatorios/operacionais'
    | '/_authenticated/relatorios/painel-geral'
    | '/_authenticated/relatorios/personalizados'
    | '/_authenticated/relatorios/propostas'
    | '/_authenticated/relatorios/simulacoes'
    | '/_authenticated/relatorios/tarefas'
    | '/_authenticated/visao-geral/painel'
    | '/api/public/sync-propostas'
    | '/_authenticated/formularios/'
    | '/_authenticated/relatorios/'
    | '/_authenticated/crm/clientes_/$id'
    | '/_authenticated/crm/clientes_/novo'
    | '/_authenticated/crm/scan-ia_/$id'
    | '/_authenticated/operacional/demandas_/$id'
    | '/_authenticated/operacional/demandas_/kanban'
    | '/_authenticated/operacional/propostas_/$id'
    | '/_authenticated/operacional/propostas_/enviar'
    | '/_authenticated/operacional/propostas_/kanban'
    | '/_authenticated/operacional/propostas_/nova'
    | '/_authenticated/operacional/simulacoes_/$id'
    | '/_authenticated/operacional/simulacoes_/completa'
    | '/_authenticated/operacional/simulacoes_/nova'
    | '/_authenticated/operacional/tarefas_/calendario'
    | '/_authenticated/operacional/tarefas_/kanban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  ClienteConsentimentoRoute: typeof ClienteConsentimentoRoute
  ParceiroRoute: typeof ParceiroRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PortalRoute: typeof PortalRoute
  ApiPublicSyncPropostasRoute: typeof ApiPublicSyncPropostasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro': {
      id: '/parceiro'
      path: '/parceiro'
      fullPath: '/parceiro'
      preLoaderRoute: typeof ParceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente-consentimento': {
      id: '/cliente-consentimento'
      path: '/cliente-consentimento'
      fullPath: '/cliente-consentimento'
      preLoaderRoute: typeof ClienteConsentimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/simulacoes': {
      id: '/parceiro/simulacoes'
      path: '/simulacoes'
      fullPath: '/parceiro/simulacoes'
      preLoaderRoute: typeof ParceiroSimulacoesRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/propostas': {
      id: '/parceiro/propostas'
      path: '/propostas'
      fullPath: '/parceiro/propostas'
      preLoaderRoute: typeof ParceiroPropostasRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/documentos': {
      id: '/parceiro/documentos'
      path: '/documentos'
      fullPath: '/parceiro/documentos'
      preLoaderRoute: typeof ParceiroDocumentosRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/comissoes': {
      id: '/parceiro/comissoes'
      path: '/comissoes'
      fullPath: '/parceiro/comissoes'
      preLoaderRoute: typeof ParceiroComissoesRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/parceiro/clientes': {
      id: '/parceiro/clientes'
      path: '/clientes'
      fullPath: '/parceiro/clientes'
      preLoaderRoute: typeof ParceiroClientesRouteImport
      parentRoute: typeof ParceiroRoute
    }
    '/cliente/visao-geral': {
      id: '/cliente/visao-geral'
      path: '/visao-geral'
      fullPath: '/cliente/visao-geral'
      preLoaderRoute: typeof ClienteVisaoGeralRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/logout': {
      id: '/cliente/logout'
      path: '/logout'
      fullPath: '/cliente/logout'
      preLoaderRoute: typeof ClienteLogoutRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/chat': {
      id: '/cliente/chat'
      path: '/chat'
      fullPath: '/cliente/chat'
      preLoaderRoute: typeof ClienteChatRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/acompanhar-minha-proposta': {
      id: '/cliente/acompanhar-minha-proposta'
      path: '/acompanhar-minha-proposta'
      fullPath: '/cliente/acompanhar-minha-proposta'
      preLoaderRoute: typeof ClienteAcompanharMinhaPropostaRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parceiro-inicio': {
      id: '/_authenticated/parceiro-inicio'
      path: '/parceiro-inicio'
      fullPath: '/parceiro-inicio'
      preLoaderRoute: typeof AuthenticatedParceiroInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matriculas': {
      id: '/_authenticated/matriculas'
      path: '/matriculas'
      fullPath: '/matriculas'
      preLoaderRoute: typeof AuthenticatedMatriculasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios': {
      id: '/_authenticated/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AuthenticatedFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/formularios/': {
      id: '/_authenticated/formularios/'
      path: '/'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AuthenticatedFormulariosIndexRouteImport
      parentRoute: typeof AuthenticatedFormulariosRoute
    }
    '/api/public/sync-propostas': {
      id: '/api/public/sync-propostas'
      path: '/api/public/sync-propostas'
      fullPath: '/api/public/sync-propostas'
      preLoaderRoute: typeof ApiPublicSyncPropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visao-geral/painel': {
      id: '/_authenticated/visao-geral/painel'
      path: '/visao-geral/painel'
      fullPath: '/visao-geral/painel'
      preLoaderRoute: typeof AuthenticatedVisaoGeralPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/tarefas': {
      id: '/_authenticated/relatorios/tarefas'
      path: '/tarefas'
      fullPath: '/relatorios/tarefas'
      preLoaderRoute: typeof AuthenticatedRelatoriosTarefasRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/simulacoes': {
      id: '/_authenticated/relatorios/simulacoes'
      path: '/simulacoes'
      fullPath: '/relatorios/simulacoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosSimulacoesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/propostas': {
      id: '/_authenticated/relatorios/propostas'
      path: '/propostas'
      fullPath: '/relatorios/propostas'
      preLoaderRoute: typeof AuthenticatedRelatoriosPropostasRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/personalizados': {
      id: '/_authenticated/relatorios/personalizados'
      path: '/personalizados'
      fullPath: '/relatorios/personalizados'
      preLoaderRoute: typeof AuthenticatedRelatoriosPersonalizadosRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/painel-geral': {
      id: '/_authenticated/relatorios/painel-geral'
      path: '/painel-geral'
      fullPath: '/relatorios/painel-geral'
      preLoaderRoute: typeof AuthenticatedRelatoriosPainelGeralRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/operacionais': {
      id: '/_authenticated/relatorios/operacionais'
      path: '/operacionais'
      fullPath: '/relatorios/operacionais'
      preLoaderRoute: typeof AuthenticatedRelatoriosOperacionaisRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/gerencial': {
      id: '/_authenticated/relatorios/gerencial'
      path: '/gerencial'
      fullPath: '/relatorios/gerencial'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerencialRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/financeiros': {
      id: '/_authenticated/relatorios/financeiros'
      path: '/financeiros'
      fullPath: '/relatorios/financeiros'
      preLoaderRoute: typeof AuthenticatedRelatoriosFinanceirosRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/exportacoes': {
      id: '/_authenticated/relatorios/exportacoes'
      path: '/exportacoes'
      fullPath: '/relatorios/exportacoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosExportacoesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/demandas': {
      id: '/_authenticated/relatorios/demandas'
      path: '/demandas'
      fullPath: '/relatorios/demandas'
      preLoaderRoute: typeof AuthenticatedRelatoriosDemandasRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/crm': {
      id: '/_authenticated/relatorios/crm'
      path: '/crm'
      fullPath: '/relatorios/crm'
      preLoaderRoute: typeof AuthenticatedRelatoriosCrmRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/consolidado': {
      id: '/_authenticated/relatorios/consolidado'
      path: '/consolidado'
      fullPath: '/relatorios/consolidado'
      preLoaderRoute: typeof AuthenticatedRelatoriosConsolidadoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/comissoes': {
      id: '/_authenticated/relatorios/comissoes'
      path: '/comissoes'
      fullPath: '/relatorios/comissoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosComissoesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/comerciais': {
      id: '/_authenticated/relatorios/comerciais'
      path: '/comerciais'
      fullPath: '/relatorios/comerciais'
      preLoaderRoute: typeof AuthenticatedRelatoriosComerciaisRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/clientes': {
      id: '/_authenticated/relatorios/clientes'
      path: '/clientes'
      fullPath: '/relatorios/clientes'
      preLoaderRoute: typeof AuthenticatedRelatoriosClientesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/app-cliente': {
      id: '/_authenticated/relatorios/app-cliente'
      path: '/app-cliente'
      fullPath: '/relatorios/app-cliente'
      preLoaderRoute: typeof AuthenticatedRelatoriosAppClienteRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/operacional/tarefas': {
      id: '/_authenticated/operacional/tarefas'
      path: '/operacional/tarefas'
      fullPath: '/operacional/tarefas'
      preLoaderRoute: typeof AuthenticatedOperacionalTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/simulacoes': {
      id: '/_authenticated/operacional/simulacoes'
      path: '/operacional/simulacoes'
      fullPath: '/operacional/simulacoes'
      preLoaderRoute: typeof AuthenticatedOperacionalSimulacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/propostas': {
      id: '/_authenticated/operacional/propostas'
      path: '/operacional/propostas'
      fullPath: '/operacional/propostas'
      preLoaderRoute: typeof AuthenticatedOperacionalPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/painel': {
      id: '/_authenticated/operacional/painel'
      path: '/operacional/painel'
      fullPath: '/operacional/painel'
      preLoaderRoute: typeof AuthenticatedOperacionalPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/demandas': {
      id: '/_authenticated/operacional/demandas'
      path: '/operacional/demandas'
      fullPath: '/operacional/demandas'
      preLoaderRoute: typeof AuthenticatedOperacionalDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/chats': {
      id: '/_authenticated/operacional/chats'
      path: '/operacional/chats'
      fullPath: '/operacional/chats'
      preLoaderRoute: typeof AuthenticatedOperacionalChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formularios/$banco': {
      id: '/_authenticated/formularios/$banco'
      path: '/$banco'
      fullPath: '/formularios/$banco'
      preLoaderRoute: typeof AuthenticatedFormulariosBancoRouteImport
      parentRoute: typeof AuthenticatedFormulariosRoute
    }
    '/_authenticated/financeiro/painel': {
      id: '/_authenticated/financeiro/painel'
      path: '/financeiro/painel'
      fullPath: '/financeiro/painel'
      preLoaderRoute: typeof AuthenticatedFinanceiroPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fluxo-de-caixa': {
      id: '/_authenticated/financeiro/fluxo-de-caixa'
      path: '/financeiro/fluxo-de-caixa'
      fullPath: '/financeiro/fluxo-de-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoDeCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-a-receber': {
      id: '/_authenticated/financeiro/contas-a-receber'
      path: '/financeiro/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-a-pagar': {
      id: '/_authenticated/financeiro/contas-a-pagar'
      path: '/financeiro/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasAPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/configuracoes': {
      id: '/_authenticated/financeiro/configuracoes'
      path: '/financeiro/configuracoes'
      fullPath: '/financeiro/configuracoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/comissoes-usuario': {
      id: '/_authenticated/financeiro/comissoes-usuario'
      path: '/financeiro/comissoes-usuario'
      fullPath: '/financeiro/comissoes-usuario'
      preLoaderRoute: typeof AuthenticatedFinanceiroComissoesUsuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/comissoes': {
      id: '/_authenticated/financeiro/comissoes'
      path: '/financeiro/comissoes'
      fullPath: '/financeiro/comissoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/scan-ia': {
      id: '/_authenticated/crm/scan-ia'
      path: '/crm/scan-ia'
      fullPath: '/crm/scan-ia'
      preLoaderRoute: typeof AuthenticatedCrmScanIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/parceiros': {
      id: '/_authenticated/crm/parceiros'
      path: '/crm/parceiros'
      fullPath: '/crm/parceiros'
      preLoaderRoute: typeof AuthenticatedCrmParceirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/painel': {
      id: '/_authenticated/crm/painel'
      path: '/crm/painel'
      fullPath: '/crm/painel'
      preLoaderRoute: typeof AuthenticatedCrmPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/documentos': {
      id: '/_authenticated/crm/documentos'
      path: '/crm/documentos'
      fullPath: '/crm/documentos'
      preLoaderRoute: typeof AuthenticatedCrmDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clientes': {
      id: '/_authenticated/crm/clientes'
      path: '/crm/clientes'
      fullPath: '/crm/clientes'
      preLoaderRoute: typeof AuthenticatedCrmClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/chat': {
      id: '/_authenticated/crm/chat'
      path: '/crm/chat'
      fullPath: '/crm/chat'
      preLoaderRoute: typeof AuthenticatedCrmChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta/seguranca': {
      id: '/_authenticated/conta/seguranca'
      path: '/conta/seguranca'
      fullPath: '/conta/seguranca'
      preLoaderRoute: typeof AuthenticatedContaSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta/perfil': {
      id: '/_authenticated/conta/perfil'
      path: '/conta/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof AuthenticatedContaPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta/notificacoes': {
      id: '/_authenticated/conta/notificacoes'
      path: '/conta/notificacoes'
      fullPath: '/conta/notificacoes'
      preLoaderRoute: typeof AuthenticatedContaNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/regras-modulos': {
      id: '/_authenticated/admin/regras-modulos'
      path: '/admin/regras-modulos'
      fullPath: '/admin/regras-modulos'
      preLoaderRoute: typeof AuthenticatedAdminRegrasModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pessoas': {
      id: '/_authenticated/admin/pessoas'
      path: '/admin/pessoas'
      fullPath: '/admin/pessoas'
      preLoaderRoute: typeof AuthenticatedAdminPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/parametros': {
      id: '/_authenticated/admin/parametros'
      path: '/admin/parametros'
      fullPath: '/admin/parametros'
      preLoaderRoute: typeof AuthenticatedAdminParametrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notificacoes': {
      id: '/_authenticated/admin/notificacoes'
      path: '/admin/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AuthenticatedAdminNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compras': {
      id: '/_authenticated/admin/compras'
      path: '/admin/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AuthenticatedAdminComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/bancos': {
      id: '/_authenticated/admin/bancos'
      path: '/admin/bancos'
      fullPath: '/admin/bancos'
      preLoaderRoute: typeof AuthenticatedAdminBancosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/admin/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/apis-ia': {
      id: '/_authenticated/admin/apis-ia'
      path: '/admin/apis-ia'
      fullPath: '/admin/apis-ia'
      preLoaderRoute: typeof AuthenticatedAdminApisIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/tarefas_/kanban': {
      id: '/_authenticated/operacional/tarefas_/kanban'
      path: '/operacional/tarefas/kanban'
      fullPath: '/operacional/tarefas/kanban'
      preLoaderRoute: typeof AuthenticatedOperacionalTarefasKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/tarefas_/calendario': {
      id: '/_authenticated/operacional/tarefas_/calendario'
      path: '/operacional/tarefas/calendario'
      fullPath: '/operacional/tarefas/calendario'
      preLoaderRoute: typeof AuthenticatedOperacionalTarefasCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/simulacoes_/nova': {
      id: '/_authenticated/operacional/simulacoes_/nova'
      path: '/operacional/simulacoes/nova'
      fullPath: '/operacional/simulacoes/nova'
      preLoaderRoute: typeof AuthenticatedOperacionalSimulacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/simulacoes_/completa': {
      id: '/_authenticated/operacional/simulacoes_/completa'
      path: '/operacional/simulacoes/completa'
      fullPath: '/operacional/simulacoes/completa'
      preLoaderRoute: typeof AuthenticatedOperacionalSimulacoesCompletaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/simulacoes_/$id': {
      id: '/_authenticated/operacional/simulacoes_/$id'
      path: '/operacional/simulacoes/$id'
      fullPath: '/operacional/simulacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacionalSimulacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/propostas_/nova': {
      id: '/_authenticated/operacional/propostas_/nova'
      path: '/operacional/propostas/nova'
      fullPath: '/operacional/propostas/nova'
      preLoaderRoute: typeof AuthenticatedOperacionalPropostasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/propostas_/kanban': {
      id: '/_authenticated/operacional/propostas_/kanban'
      path: '/operacional/propostas/kanban'
      fullPath: '/operacional/propostas/kanban'
      preLoaderRoute: typeof AuthenticatedOperacionalPropostasKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/propostas_/enviar': {
      id: '/_authenticated/operacional/propostas_/enviar'
      path: '/operacional/propostas/enviar'
      fullPath: '/operacional/propostas/enviar'
      preLoaderRoute: typeof AuthenticatedOperacionalPropostasEnviarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/propostas_/$id': {
      id: '/_authenticated/operacional/propostas_/$id'
      path: '/operacional/propostas/$id'
      fullPath: '/operacional/propostas/$id'
      preLoaderRoute: typeof AuthenticatedOperacionalPropostasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/demandas_/kanban': {
      id: '/_authenticated/operacional/demandas_/kanban'
      path: '/operacional/demandas/kanban'
      fullPath: '/operacional/demandas/kanban'
      preLoaderRoute: typeof AuthenticatedOperacionalDemandasKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacional/demandas_/$id': {
      id: '/_authenticated/operacional/demandas_/$id'
      path: '/operacional/demandas/$id'
      fullPath: '/operacional/demandas/$id'
      preLoaderRoute: typeof AuthenticatedOperacionalDemandasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/scan-ia_/$id': {
      id: '/_authenticated/crm/scan-ia_/$id'
      path: '/crm/scan-ia/$id'
      fullPath: '/crm/scan-ia/$id'
      preLoaderRoute: typeof AuthenticatedCrmScanIaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clientes_/novo': {
      id: '/_authenticated/crm/clientes_/novo'
      path: '/crm/clientes/novo'
      fullPath: '/crm/clientes/novo'
      preLoaderRoute: typeof AuthenticatedCrmClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clientes_/$id': {
      id: '/_authenticated/crm/clientes_/$id'
      path: '/crm/clientes/$id'
      fullPath: '/crm/clientes/$id'
      preLoaderRoute: typeof AuthenticatedCrmClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFormulariosRouteChildren {
  AuthenticatedFormulariosBancoRoute: typeof AuthenticatedFormulariosBancoRoute
  AuthenticatedFormulariosIndexRoute: typeof AuthenticatedFormulariosIndexRoute
}

const AuthenticatedFormulariosRouteChildren: AuthenticatedFormulariosRouteChildren =
  {
    AuthenticatedFormulariosBancoRoute: AuthenticatedFormulariosBancoRoute,
    AuthenticatedFormulariosIndexRoute: AuthenticatedFormulariosIndexRoute,
  }

const AuthenticatedFormulariosRouteWithChildren =
  AuthenticatedFormulariosRoute._addFileChildren(
    AuthenticatedFormulariosRouteChildren,
  )

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosAppClienteRoute: typeof AuthenticatedRelatoriosAppClienteRoute
  AuthenticatedRelatoriosClientesRoute: typeof AuthenticatedRelatoriosClientesRoute
  AuthenticatedRelatoriosComerciaisRoute: typeof AuthenticatedRelatoriosComerciaisRoute
  AuthenticatedRelatoriosComissoesRoute: typeof AuthenticatedRelatoriosComissoesRoute
  AuthenticatedRelatoriosConsolidadoRoute: typeof AuthenticatedRelatoriosConsolidadoRoute
  AuthenticatedRelatoriosCrmRoute: typeof AuthenticatedRelatoriosCrmRoute
  AuthenticatedRelatoriosDemandasRoute: typeof AuthenticatedRelatoriosDemandasRoute
  AuthenticatedRelatoriosExportacoesRoute: typeof AuthenticatedRelatoriosExportacoesRoute
  AuthenticatedRelatoriosFinanceirosRoute: typeof AuthenticatedRelatoriosFinanceirosRoute
  AuthenticatedRelatoriosGerencialRoute: typeof AuthenticatedRelatoriosGerencialRoute
  AuthenticatedRelatoriosOperacionaisRoute: typeof AuthenticatedRelatoriosOperacionaisRoute
  AuthenticatedRelatoriosPainelGeralRoute: typeof AuthenticatedRelatoriosPainelGeralRoute
  AuthenticatedRelatoriosPersonalizadosRoute: typeof AuthenticatedRelatoriosPersonalizadosRoute
  AuthenticatedRelatoriosPropostasRoute: typeof AuthenticatedRelatoriosPropostasRoute
  AuthenticatedRelatoriosSimulacoesRoute: typeof AuthenticatedRelatoriosSimulacoesRoute
  AuthenticatedRelatoriosTarefasRoute: typeof AuthenticatedRelatoriosTarefasRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosAppClienteRoute:
      AuthenticatedRelatoriosAppClienteRoute,
    AuthenticatedRelatoriosClientesRoute: AuthenticatedRelatoriosClientesRoute,
    AuthenticatedRelatoriosComerciaisRoute:
      AuthenticatedRelatoriosComerciaisRoute,
    AuthenticatedRelatoriosComissoesRoute:
      AuthenticatedRelatoriosComissoesRoute,
    AuthenticatedRelatoriosConsolidadoRoute:
      AuthenticatedRelatoriosConsolidadoRoute,
    AuthenticatedRelatoriosCrmRoute: AuthenticatedRelatoriosCrmRoute,
    AuthenticatedRelatoriosDemandasRoute: AuthenticatedRelatoriosDemandasRoute,
    AuthenticatedRelatoriosExportacoesRoute:
      AuthenticatedRelatoriosExportacoesRoute,
    AuthenticatedRelatoriosFinanceirosRoute:
      AuthenticatedRelatoriosFinanceirosRoute,
    AuthenticatedRelatoriosGerencialRoute:
      AuthenticatedRelatoriosGerencialRoute,
    AuthenticatedRelatoriosOperacionaisRoute:
      AuthenticatedRelatoriosOperacionaisRoute,
    AuthenticatedRelatoriosPainelGeralRoute:
      AuthenticatedRelatoriosPainelGeralRoute,
    AuthenticatedRelatoriosPersonalizadosRoute:
      AuthenticatedRelatoriosPersonalizadosRoute,
    AuthenticatedRelatoriosPropostasRoute:
      AuthenticatedRelatoriosPropostasRoute,
    AuthenticatedRelatoriosSimulacoesRoute:
      AuthenticatedRelatoriosSimulacoesRoute,
    AuthenticatedRelatoriosTarefasRoute: AuthenticatedRelatoriosTarefasRoute,
    AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedFormulariosRoute: typeof AuthenticatedFormulariosRouteWithChildren
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedMatriculasRoute: typeof AuthenticatedMatriculasRoute
  AuthenticatedParceiroInicioRoute: typeof AuthenticatedParceiroInicioRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedRhRoute: typeof AuthenticatedRhRoute
  AuthenticatedAdminApisIaRoute: typeof AuthenticatedAdminApisIaRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminBancosRoute: typeof AuthenticatedAdminBancosRoute
  AuthenticatedAdminComprasRoute: typeof AuthenticatedAdminComprasRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminNotificacoesRoute: typeof AuthenticatedAdminNotificacoesRoute
  AuthenticatedAdminParametrosRoute: typeof AuthenticatedAdminParametrosRoute
  AuthenticatedAdminPessoasRoute: typeof AuthenticatedAdminPessoasRoute
  AuthenticatedAdminRegrasModulosRoute: typeof AuthenticatedAdminRegrasModulosRoute
  AuthenticatedContaNotificacoesRoute: typeof AuthenticatedContaNotificacoesRoute
  AuthenticatedContaPerfilRoute: typeof AuthenticatedContaPerfilRoute
  AuthenticatedContaSegurancaRoute: typeof AuthenticatedContaSegurancaRoute
  AuthenticatedCrmChatRoute: typeof AuthenticatedCrmChatRoute
  AuthenticatedCrmClientesRoute: typeof AuthenticatedCrmClientesRoute
  AuthenticatedCrmDocumentosRoute: typeof AuthenticatedCrmDocumentosRoute
  AuthenticatedCrmPainelRoute: typeof AuthenticatedCrmPainelRoute
  AuthenticatedCrmParceirosRoute: typeof AuthenticatedCrmParceirosRoute
  AuthenticatedCrmScanIaRoute: typeof AuthenticatedCrmScanIaRoute
  AuthenticatedFinanceiroComissoesRoute: typeof AuthenticatedFinanceiroComissoesRoute
  AuthenticatedFinanceiroComissoesUsuarioRoute: typeof AuthenticatedFinanceiroComissoesUsuarioRoute
  AuthenticatedFinanceiroConfiguracoesRoute: typeof AuthenticatedFinanceiroConfiguracoesRoute
  AuthenticatedFinanceiroContasAPagarRoute: typeof AuthenticatedFinanceiroContasAPagarRoute
  AuthenticatedFinanceiroContasAReceberRoute: typeof AuthenticatedFinanceiroContasAReceberRoute
  AuthenticatedFinanceiroFluxoDeCaixaRoute: typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  AuthenticatedFinanceiroPainelRoute: typeof AuthenticatedFinanceiroPainelRoute
  AuthenticatedOperacionalChatsRoute: typeof AuthenticatedOperacionalChatsRoute
  AuthenticatedOperacionalDemandasRoute: typeof AuthenticatedOperacionalDemandasRoute
  AuthenticatedOperacionalPainelRoute: typeof AuthenticatedOperacionalPainelRoute
  AuthenticatedOperacionalPropostasRoute: typeof AuthenticatedOperacionalPropostasRoute
  AuthenticatedOperacionalSimulacoesRoute: typeof AuthenticatedOperacionalSimulacoesRoute
  AuthenticatedOperacionalTarefasRoute: typeof AuthenticatedOperacionalTarefasRoute
  AuthenticatedVisaoGeralPainelRoute: typeof AuthenticatedVisaoGeralPainelRoute
  AuthenticatedCrmClientesIdRoute: typeof AuthenticatedCrmClientesIdRoute
  AuthenticatedCrmClientesNovoRoute: typeof AuthenticatedCrmClientesNovoRoute
  AuthenticatedCrmScanIaIdRoute: typeof AuthenticatedCrmScanIaIdRoute
  AuthenticatedOperacionalDemandasIdRoute: typeof AuthenticatedOperacionalDemandasIdRoute
  AuthenticatedOperacionalDemandasKanbanRoute: typeof AuthenticatedOperacionalDemandasKanbanRoute
  AuthenticatedOperacionalPropostasIdRoute: typeof AuthenticatedOperacionalPropostasIdRoute
  AuthenticatedOperacionalPropostasEnviarRoute: typeof AuthenticatedOperacionalPropostasEnviarRoute
  AuthenticatedOperacionalPropostasKanbanRoute: typeof AuthenticatedOperacionalPropostasKanbanRoute
  AuthenticatedOperacionalPropostasNovaRoute: typeof AuthenticatedOperacionalPropostasNovaRoute
  AuthenticatedOperacionalSimulacoesIdRoute: typeof AuthenticatedOperacionalSimulacoesIdRoute
  AuthenticatedOperacionalSimulacoesCompletaRoute: typeof AuthenticatedOperacionalSimulacoesCompletaRoute
  AuthenticatedOperacionalSimulacoesNovaRoute: typeof AuthenticatedOperacionalSimulacoesNovaRoute
  AuthenticatedOperacionalTarefasCalendarioRoute: typeof AuthenticatedOperacionalTarefasCalendarioRoute
  AuthenticatedOperacionalTarefasKanbanRoute: typeof AuthenticatedOperacionalTarefasKanbanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedFormulariosRoute: AuthenticatedFormulariosRouteWithChildren,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedMatriculasRoute: AuthenticatedMatriculasRoute,
  AuthenticatedParceiroInicioRoute: AuthenticatedParceiroInicioRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedRhRoute: AuthenticatedRhRoute,
  AuthenticatedAdminApisIaRoute: AuthenticatedAdminApisIaRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
  AuthenticatedAdminBancosRoute: AuthenticatedAdminBancosRoute,
  AuthenticatedAdminComprasRoute: AuthenticatedAdminComprasRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminNotificacoesRoute: AuthenticatedAdminNotificacoesRoute,
  AuthenticatedAdminParametrosRoute: AuthenticatedAdminParametrosRoute,
  AuthenticatedAdminPessoasRoute: AuthenticatedAdminPessoasRoute,
  AuthenticatedAdminRegrasModulosRoute: AuthenticatedAdminRegrasModulosRoute,
  AuthenticatedContaNotificacoesRoute: AuthenticatedContaNotificacoesRoute,
  AuthenticatedContaPerfilRoute: AuthenticatedContaPerfilRoute,
  AuthenticatedContaSegurancaRoute: AuthenticatedContaSegurancaRoute,
  AuthenticatedCrmChatRoute: AuthenticatedCrmChatRoute,
  AuthenticatedCrmClientesRoute: AuthenticatedCrmClientesRoute,
  AuthenticatedCrmDocumentosRoute: AuthenticatedCrmDocumentosRoute,
  AuthenticatedCrmPainelRoute: AuthenticatedCrmPainelRoute,
  AuthenticatedCrmParceirosRoute: AuthenticatedCrmParceirosRoute,
  AuthenticatedCrmScanIaRoute: AuthenticatedCrmScanIaRoute,
  AuthenticatedFinanceiroComissoesRoute: AuthenticatedFinanceiroComissoesRoute,
  AuthenticatedFinanceiroComissoesUsuarioRoute:
    AuthenticatedFinanceiroComissoesUsuarioRoute,
  AuthenticatedFinanceiroConfiguracoesRoute:
    AuthenticatedFinanceiroConfiguracoesRoute,
  AuthenticatedFinanceiroContasAPagarRoute:
    AuthenticatedFinanceiroContasAPagarRoute,
  AuthenticatedFinanceiroContasAReceberRoute:
    AuthenticatedFinanceiroContasAReceberRoute,
  AuthenticatedFinanceiroFluxoDeCaixaRoute:
    AuthenticatedFinanceiroFluxoDeCaixaRoute,
  AuthenticatedFinanceiroPainelRoute: AuthenticatedFinanceiroPainelRoute,
  AuthenticatedOperacionalChatsRoute: AuthenticatedOperacionalChatsRoute,
  AuthenticatedOperacionalDemandasRoute: AuthenticatedOperacionalDemandasRoute,
  AuthenticatedOperacionalPainelRoute: AuthenticatedOperacionalPainelRoute,
  AuthenticatedOperacionalPropostasRoute:
    AuthenticatedOperacionalPropostasRoute,
  AuthenticatedOperacionalSimulacoesRoute:
    AuthenticatedOperacionalSimulacoesRoute,
  AuthenticatedOperacionalTarefasRoute: AuthenticatedOperacionalTarefasRoute,
  AuthenticatedVisaoGeralPainelRoute: AuthenticatedVisaoGeralPainelRoute,
  AuthenticatedCrmClientesIdRoute: AuthenticatedCrmClientesIdRoute,
  AuthenticatedCrmClientesNovoRoute: AuthenticatedCrmClientesNovoRoute,
  AuthenticatedCrmScanIaIdRoute: AuthenticatedCrmScanIaIdRoute,
  AuthenticatedOperacionalDemandasIdRoute:
    AuthenticatedOperacionalDemandasIdRoute,
  AuthenticatedOperacionalDemandasKanbanRoute:
    AuthenticatedOperacionalDemandasKanbanRoute,
  AuthenticatedOperacionalPropostasIdRoute:
    AuthenticatedOperacionalPropostasIdRoute,
  AuthenticatedOperacionalPropostasEnviarRoute:
    AuthenticatedOperacionalPropostasEnviarRoute,
  AuthenticatedOperacionalPropostasKanbanRoute:
    AuthenticatedOperacionalPropostasKanbanRoute,
  AuthenticatedOperacionalPropostasNovaRoute:
    AuthenticatedOperacionalPropostasNovaRoute,
  AuthenticatedOperacionalSimulacoesIdRoute:
    AuthenticatedOperacionalSimulacoesIdRoute,
  AuthenticatedOperacionalSimulacoesCompletaRoute:
    AuthenticatedOperacionalSimulacoesCompletaRoute,
  AuthenticatedOperacionalSimulacoesNovaRoute:
    AuthenticatedOperacionalSimulacoesNovaRoute,
  AuthenticatedOperacionalTarefasCalendarioRoute:
    AuthenticatedOperacionalTarefasCalendarioRoute,
  AuthenticatedOperacionalTarefasKanbanRoute:
    AuthenticatedOperacionalTarefasKanbanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClienteRouteChildren {
  ClienteAcompanharMinhaPropostaRoute: typeof ClienteAcompanharMinhaPropostaRoute
  ClienteChatRoute: typeof ClienteChatRoute
  ClienteLogoutRoute: typeof ClienteLogoutRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteVisaoGeralRoute: typeof ClienteVisaoGeralRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAcompanharMinhaPropostaRoute: ClienteAcompanharMinhaPropostaRoute,
  ClienteChatRoute: ClienteChatRoute,
  ClienteLogoutRoute: ClienteLogoutRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteVisaoGeralRoute: ClienteVisaoGeralRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface ParceiroRouteChildren {
  ParceiroClientesRoute: typeof ParceiroClientesRoute
  ParceiroComissoesRoute: typeof ParceiroComissoesRoute
  ParceiroDocumentosRoute: typeof ParceiroDocumentosRoute
  ParceiroPropostasRoute: typeof ParceiroPropostasRoute
  ParceiroSimulacoesRoute: typeof ParceiroSimulacoesRoute
}

const ParceiroRouteChildren: ParceiroRouteChildren = {
  ParceiroClientesRoute: ParceiroClientesRoute,
  ParceiroComissoesRoute: ParceiroComissoesRoute,
  ParceiroDocumentosRoute: ParceiroDocumentosRoute,
  ParceiroPropostasRoute: ParceiroPropostasRoute,
  ParceiroSimulacoesRoute: ParceiroSimulacoesRoute,
}

const ParceiroRouteWithChildren = ParceiroRoute._addFileChildren(
  ParceiroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRouteWithChildren,
  ClienteConsentimentoRoute: ClienteConsentimentoRoute,
  ParceiroRoute: ParceiroRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PortalRoute: PortalRoute,
  ApiPublicSyncPropostasRoute: ApiPublicSyncPropostasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
